### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by belfz** [polkadot-js/common#1011]
I tried using the code [from the example](https://polkadot.js.org/docs/util-crypto/examples/validate-address/) in my react + typescript project, but while I fire up my tests (with jest) I get the following error:

```
/Users/marcin/projects/admin-ui/node_modules/@polkadot/keyring/index.js:3
    import "./detectPackage.js";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

Does it require some special typescript configuration?

**Comment by jacogr** [comment]
Jest has issues with ESM (27 does it better). This is what this repo uses to get Jest to play nicely with import maps - https://github.com/polkadot-js/common/blob/master/jest.config.cjs#L35

**Comment by belfz** [comment]
How am I supposed to "map" these modules when I use @polkadot/util & @polkadot/keyring as libraries in my project? The linked config doesn't seem to be helpful in my case.

**Comment by jacogr** [comment]
Exactly like the line I showed above - `transformIgnorePatterns: ['/node_modules/(?!@polkadot)']`

This tells jest to not try and transform based on the matched pattern in node modules.

**Comment by belfz** [comment]
Added this line to my jest config, it doesn't change anything (still getting the same error).
I'm on jest 24.8.0.

**Comment by jacogr** [comment]
The above is the only level I had to tweak to get Jest to play nicely with ESM. They do have a page around esm support (and a number of issues logged by their users), so best I can suggest is to refer to that. 

(27.x does improve support dramatically from what I've seen from other reports, with the above flag I have seen no difference between 26 and 27)

**Comment by ChaosAmd** [comment]
Hello, I went through the same problem and I solved by adding more patterns on transform:
```
  transformIgnorePatterns: [
    '/node_modules/(?!@polkadot|@babel/runtime/helpers/esm/)'
  ]
  ```
  Using jest 27.0.4 here.
