### ISSUE TITLE
Java offline generation polkadot address 

### ISSUE THREAD

**Issue by liutianv1** [polkadot-js/common#1023]
i use SCALE Codec for java generation offline address. but i generation address and polkadot.js generation address is not like；
i use bitcoinj 's MnemonicCode generation mnemonic,and i toseed the mnemonic get seed；
this is my code；

https://stackoverflow.com/questions/68092665/java-offline-generation-wave-card-address

polkadot.js generation'address is "12EgmkT6NHjTjtwcvfBFu1dkPEN9TLFo3ftA4L2ZcmkCfQCp";

i use my code generation'address is "12YTJRjPRsw34wBp2Ewfr9oBP9w47RpKKw4CPZF2zaCga1Hk"

help help help

how i do can generation like polkadot.js' address ?

**Comment by liutianv1** [comment]
help me  ,thank everyone

**Comment by jacogr** [comment]
The process is -

mnemonic
mnemonic -> entropy
entropy -> minisecret (with pbkdf2)
minisecret -> pair

See https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/mnemonic/toMiniSecret.ts#L18-L22

The entropy usage is different from other cryptocurrency chains, i.e. there they always go to seed.

**Comment by liutianv1** [comment]
OK，thank U brother

**Comment by liutianv1** [comment]
> secret

hello ,brother. entropy -> minisecret (with pbkdf2)? how did i do for java

**Comment by liutianv1** [comment]
@jacogr

**Comment by liutianv1** [comment]
help , this week i must done my work.

**Comment by jacogr** [comment]
No idea, last time I did any Java was in 2006, 15 years ago.

**Comment by liutianv1** [comment]
@jacogr OK ，Im try . thanks

**Comment by liutianv1** [comment]
@jacogr borther，Are U online ? Can I debug with you at the same time？I use java ，U use js。Let's go through it step by step
