### ISSUE TITLE
what happened to Blake2s implementation in util-crypto

### ISSUE THREAD

**Issue by kkast** [polkadot-js/common#1039]
Hi! at the moment '@polkadot/util-crypto' only provides blake2AsU8a which is blake2b.  there was a pr https://github.com/polkadot-js/common/pull/66/files#diff-67db38e15c39a4981b3e9bae48f7862ff87fca1080fc2abd3904bb12a2800be8R34 which had Blake2s added. On the substrate side, there is an opportunity to use blake2s. Could you please tell me if there is an implementation of blake2s by polkadot-js, and if not, was there particular reason to remove it. Are there recommendations to use blake2b? If no, what package would be considered good to be used for blake2s with up to date support? Thank you for your time!

**Comment by jacogr** [comment]
I will need to look at the history - but if I had to guess (without looking at the PRs), it was because Substrate only uses 2b. So basically 2s was “unused”. 

The Blake-JS package works really well. 

Can certainly add 2s back if there is a need.

**Comment by kkast** [comment]
@jacogr thank you very much for your response! Are you referring https://github.com/dcposch/blakejs?
in substrate there is pallet called blake2 and it also support Blake2s. Is it recommended to use Blake2b on substrate?

**Comment by jacogr** [comment]
Yes, on the JS side it either uses -

- blakejs (when WASM is not available), or
- Rust blake2_rfc via WASM (when WASM is available, same crate as in Substrate)

I cannot say what is recommended, only that Substrate/Polkadot only uses 2b everywhere Blake is used (which is the default for all hashing operations).
