### ISSUE TITLE
Question: How to test local changes.

### ISSUE THREAD

**Issue by ghzlatarev** [polkadot-js/common#1064]
Hey guys, I've got a simple question. 

How can I test some changes that I've made to local clone of the repo?
For example in https://github.com/polkadot-js/common/blob/master/packages/networks/src/index.ts#L14-L24
I'd like to deploy the polkadot js extension locally and check console logs.

Not very familiar with TS and how the code is organized.

Thanks for the attention.

**Comment by jacogr** [comment]
If you wish to copy the common utils to another repo, ensure you have this structure -

```
<ROOTDIR>/
<ROOTDIR>/common
<ROOTDIR>/extension
...
```

Then inside the common directory you can do `yarn polkadot-dev-copy-to extension` and it will compile and copy the packages into the correct locations.

**Comment by ghzlatarev** [comment]
Thanks for the reply.
So I understood how to build it locally and install that local version in Chrome.

However i'm still having difficulty with integrating changes in ``common`` repo. 
Locally I have the structure you have mentioned:
```
<ROOTDIR>/
<ROOTDIR>/common
<ROOTDIR>/extension
...
```
Then i go to ``common`` repo, change the code and hit `` yarn polkadot-dev-copy-to extension `` .
 All good so far, files get copied ``extension/node_modules/``
 
 But now when I try ``yarn build`` in the ``extensions`` repo I get a ton of errors like:
 ```
 packages/extension-base/src/background/RequestBytesSign.ts:4:34 - error TS7016: Could not find a declaration file for module '@polkadot/keyring/types'. '/home/georgi/Desktop/workspace/Parity/Polkadot_JS/extension/node_modules/@polkadot/keyring/types.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/polkadot__keyring` if it exists or add a new declaration (.d.ts) file containing `declare module '@polkadot/keyring/types';`

4 import type { KeyringPair } from '@polkadot/keyring/types';
 ```
or

```
packages/extension-ui/src/components/Address.tsx:19:46 - error TS7016: Could not find a declaration file for module '@polkadot/util-crypto'. '/home/georgi/Desktop/workspace/Parity/Polkadot_JS/extension/node_modules/@polkadot/util-crypto/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/polkadot__util-crypto` if it exists or add a new declaration (.d.ts) file containing `declare module '@polkadot/util-crypto';`

19 import { decodeAddress, encodeAddress } from '@polkadot/util-crypto';
                                                ~~~~~~~~~~~~~~~~~~~~~~~
```

Any idea how to resolve these ? Or if i'm missing something in the process ?

**Comment by ghzlatarev** [comment]
1 more update. All these errors seem to be because of missing ``.d.ts`` files.
When I clone the ``extension`` repo I run ``yarn`` and cached all the ``.d.ts`` files.
Then I ran your suggestion for ``yarn polkadot-dev-copy-to extension`` in ``common`` repo, which overwrites everything in ``/extension/node-modules/`` deleting all the ``.d.ts`` files.
So then I just copied the once I stashed at the beginning and all the errors cleared and my updated code is integrated, ie my logs are showing up.

I still don't understand what i'm doing wrong in the first place though. How can i generate those ``.d.ts`` files automatically ?

**Comment by ghzlatarev** [comment]
A couple of things that i'm exploring.

-Maybe your command ``yarn polkadot-dev-copy-to extension`` doesn't copy ``.ts`` files on purpose and I can hack it to do so ?
-Installing the missing types with ``npm install --save-dev  @polkadot/keyring/types`` or something similar ? But it is error-ing out with errors like ``Could not install from "@polkadot/keyring/types" as it does not contain a package.json file.``

Any suggestions ?

**Comment by jacogr** [comment]
So there was def. a bump missing to latest, i.e. this PR - https://github.com/polkadot-js/extension/pull/785

However, the above should not happen. So on master (after the above is merged), just ensure to do a `yarn` and then `yarn build` to see if it works before copy.

**Comment by ghzlatarev** [comment]
So, pulled the latest master in ``extension`` and ran `` yarn `` and `` yarn build `` . Everything compiled - check.

But then I go to the ``common`` repo and run ``yarn polkadot-dev-copy-to extension`` and this again overwrites all the ``.d.ts`` files in ``extension/node-modules/`` and I get the same errors.

**Comment by ghzlatarev** [comment]
So I basically wrote a script that does:

1. build common
2. copy some files to extension
3. build extension

Then I just work in ``common`` and add new files when I modify/need them. Kinda lame but got me to sort of acceptable iterations speed.

Still interested in finding what i'm doing wrong in the first place if you find the time, otherwise we can close this.

Thanks for the help.
