### ISSUE TITLE
How to pass polkadot-js Obtain the private key of the Polkadot account?

### ISSUE THREAD

**Issue by pengbin9472** [polkadot-js/common#1067]
The following code:

const pair = keyring.createFromUri(mnemonic);

I want to get the private key by pair,Let me know if you have any other way,Please show me your code, it will be very helpful to me, thanks in advance

**Comment by RoyTimes** [comment]
adding on to that, is it possible to use the browser extension to do encrypt/decrypt with the private key. The Dapp won't necessarily need to obtain the private key.

**Comment by jacogr** [comment]
polkadot-js extension only allows signing of either data or transactions. There is no sr25519 encrypt/decrypt operations exposed.

**Comment by RoyTimes** [comment]
Any plans of implementing that? It's essential to an Dapp I'm working on. I can draft a PR if such feature is ok to be added to the browser extension.
