### ISSUE TITLE
How to generate polkadot address from xpub

### ISSUE THREAD

**Issue by chenxing-luckysky** [polkadot-js/common#1071]
I was building a HD Wallet, and derivate some xpub to create wallet for different coins. polkadot is one of the coins. and I can't find any recourses to generate address from this xpub?
function xpubToDotAddress(xpub){
   ...logic here;
   return address;
}
for example: 
for btc, I have
function xpubToBtcAddress(xpub) {
  const node = HDKEY.fromExtendedKey(xpub);
  const { address } = bitcoinjs.payments.p2pkh({ pubkey: node.publicKey });
  return address;
}
So How can i generate dot address from xpub

**Comment by jacogr** [comment]
Substrate has an own derivation scheme, it doesn't use the Bitcoin derivations.

**Comment by chenxing-luckysky** [comment]
Thank you for your help. I solve the problem!
