### ISSUE TITLE
Versions >v5 have a runtime error when bundled with parcel v2

### ISSUE THREAD

**Issue by raoulmillais** [polkadot-js/common#1075]
Parcel creates the bundle fine but then at runtime we get this error:

```javascript
esmodule-helpers.js:20 Uncaught TypeError: Cannot redefine property: packageInfo
    at Function.defineProperty (<anonymous>)
    at index.8b0b0307.js:1313
    at Array.forEach (<anonymous>)
    at Object.exports.exportAll (index.8b0b0307.js:1309)
    at Object.aPLML../cryptoInit.js (index.8b0b0307.js:9554)
    at newRequire (index.8b0b0307.js:71)
    at localRequire (index.8b0b0307.js:83)
    at Object.46Hog../detectPackage.js (index.8b0b0307.js:9470)
    at newRequire (index.8b0b0307.js:71)
    at localRequire (index.8b0b0307.js:83)
```

I've uploaded the bundle [here](https://gist.github.com/raoulmillais/43d8c89bf62aa61bff8c6df4d23643ec)

I tried hard to get a more specific stacktrace for you but I got stuck.  The published version of @polkadot/api has no sourcemaps.  
* I can't `yarn link` from a local @polkadot/api into @substrate/connect because we use yarn "classic" and that won't work from a yarn "berry" repository.  
* I then tried to create a minimal repo using yarn berry and parcel 2 with @polkadot/api linked in but discovered sourcemaps aren't enabled in the [polkadot dev rollup script](https://github.com/polkadot-js/dev/blob/master/packages/dev/config/rollup.js#L42-L51)
* I then tried adding it to dev .. linking it into api .. rebuilding API but I got cryptic yarn errors when runnning the build.

At this point I've given up .. but maybe you can see quickly what the problem is ?  or if not give me some pointers about how to best use the polkadot dev scripts to make changes locally like this across these polkadot repos and test them?

**Comment by jacogr** [comment]
It is a bug - it should re-export everything apart from `packageInfo`
