### ISSUE TITLE
Use the `bigint` type instead of `BigInt`

### ISSUE THREAD

**Issue by ntduan** [polkadot-js/common#1080]
I know this PR. https://github.com/polkadot-js/api/pull/3047
But it seems that there are still many BigInt types in the project.
According to the typescript documentation: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#bigint.
The `BigInt` type is the type of the constructor. `bigint` is the type of the value. Just like the difference between `Number` and `number`.
So I think we should replace almost all BigInt types with bigint to avoid type errors.

![image](https://user-images.githubusercontent.com/7029338/129132489-b789ca19-a62c-4102-8daf-b8ccdd848643.png)

**Comment by jacogr** [comment]
Resolved in common, api & ui repos. Thank you.
