### ISSUE TITLE
Inaccurate ECDSA ss58 encoding

### ISSUE THREAD

**Issue by h4x3rotab** [polkadot-js/common#1099]
In this line, it assumes a 33-bytes ecdsa public key must be hashed before encoding:

https://github.com/polkadot-js/common/blob/f0b984f1413559b3ed0c31bafbe4d09cb88ce51a/packages/keyring/src/pair/index.ts#L45

Not sure if this is true for Ethereum addresses, but it's incorrect for beefy id. The ss58 encoding of a ecdsa key defined in Substrate doesn't have any hash applied:

https://github.com/paritytech/substrate/blob/ab84c8cfe8511ef9f8e5ffb8a497383f4b008daa/primitives/core/src/crypto.rs#L296-L315

## Test vector

- Uri: `//Alice`
- Expected output: `KW39r9CJjAVzmkf9zQ4YDb2hqfAVGdRqn53eRqyruqpxAP5YL`
- Actual output: `5C7C2Z5sWbytvHpuLTvzKunnnRwQxft1jiqrLD5rhucQ5S9X`

If you run `subkey inspect 5C7C2Z5sWbytvHpuLTvzKunnnRwQxft1jiqrLD5rhucQ5S9X --scheme Ecdsa`, it complains:

```
Invalid phrase/URI given
```

But if you run `subkey inspect KW39r9CJjAVzmkf9zQ4YDb2hqfAVGdRqn53eRqyruqpxAP5YL --scheme Ecdsa`, it gives out the correct decoding:

```
Public Key URI `KW39r9CJjAVzmkf9zQ4YDb2hqfAVGdRqn53eRqyruqpxAP5YL` is account:
  Network ID/version: substrate
  Public key (hex):   0x020a1091341fe5664bfa1782d5e04779689068c916b04cb365ec3153755684d9a1
  Public key (SS58):  KW39r9CJjAVzmkf9zQ4YDb2hqfAVGdRqn53eRqyruqpxAP5YL
  Account ID:         0x01e552298e47454041ea31273b4b630c64c104e4514aa3643490b8aaca9cf8ed
  SS58 Address:       KW39r9CJjAVzmkf9zQ4YDb2hqfAVGdRqn53eRqyruqpxAP5YL
```

**Comment by jacogr** [comment]
```
$ cargo run --release -p subkey -- inspect "//Alice" --scheme Ecdsa 
    Finished release [optimized] target(s) in 0.58s
     Running `target/release/subkey inspect //Alice --scheme Ecdsa`
Secret Key URI `//Alice` is account:
  Secret seed:       0xcb6df9de1efca7a3998a8ead4e02159d5fa99c3e0d4fd6432667390bb4726854
  Public key (hex):  0x020a1091341fe5664bfa1782d5e04779689068c916b04cb365ec3153755684d9a1
  Public key (SS58): KW39r9CJjAVzmkf9zQ4YDb2hqfAVGdRqn53eRqyruqpxAP5YL
  Account ID:        0x01e552298e47454041ea31273b4b630c64c104e4514aa3643490b8aaca9cf8ed
  SS58 Address:      5C7C2Z5sWbytvHpuLTvzKunnnRwQxft1jiqrLD5rhucQ5S9X
  ```

See the address above, it matches with the address in your example.

**Comment by h4x3rotab** [comment]
Got it. So pubkey(ss58) is what I really need. Thanks for the explanation.
