### ISSUE TITLE
Ethereum derivation returns incorrect address

### ISSUE THREAD

**Issue by albertov19** [polkadot-js/common#1118]
When trying the following code the address derived from a mnemonic is no the expected one. Check the code below and the logs and expected derivations.

```
// Import Ethereum Account from Private Key
import Keyring from '@polkadot/keyring';
import { u8aToHex } from '@polkadot/util';
import { mnemonicToMiniSecret } from '@polkadot/util-crypto';

const keyring = new Keyring({ type: 'ethereum' });

// Import from Mnemonic
const mnemonic =
  'fantasy essence ordinary warfare eagle tortoise priority prepare ethics brave wide destroy';

console.log(`Mnemonic: ${mnemonic}`);

const newPair = keyring.createFromUri(mnemonic);
console.log(`Derived Address from Mnemonic: ${newPair.address}`);

// Extract private key from mnemonic
const privateKey = u8aToHex(mnemonicToMiniSecret(mnemonic));
console.log(`Derived Private Key from Mnemonic: ${privateKey}`);

const otherPair = await keyring.addFromUri(privateKey);
console.log(`Derived Address from Private Key: ${otherPair.address}`);
```

**Obtained log**
Mnemonic: fantasy essence ordinary warfare eagle tortoise priority prepare ethics brave wide destroy
Derived Address from Mnemonic: 0x6392417A199C347Bad3b0454dB122405c8a8DAd6
Derived Private Key from Mnemonic: 0xbb3f30e7609f793f8bb61d5a77f5612d99388e33cd979880973d85f3882119af
Derived Address from Private Key: 0x38cA3e4A89209161F18dDF81a442cf19975F695d

**Deriving it using some derivation tools**
Expected Address: 0x78C9c3E21d94ffc43ef7039038F4D8D807576EdC
Expected Private Key: 0x1f15bcafd50058293dc4716341754d82ba66419d824b0ed82fbbda1375af4135

**Using Moonkey**
Derived Address from Mnemonic: 0x78c9c3e21d94ffc43ef7039038f4d8d807576edc
Derived Private Key from Mnemonic: 0x1f15bcafd50058293dc4716341754d82ba66419d824b0ed82fbbda1375af4135

**Comment by jacogr** [comment]
`mnemonicToMiniSecret` is incorrect - that is the Substrate format.

If you add via the keyring, it will follow the correct (legacy seed) derivation path.

**Comment by albertov19** [comment]
Understood. I'm still unable to get the correct address from the mnemonic tho. Looking at the code I need to manually specify the derivation path as follows:

```
// Import Ethereum Account from Private Key
import Keyring from '@polkadot/keyring';
import { u8aToHex } from '@polkadot/util';
import { mnemonicToLegacySeed } from '@polkadot/util-crypto';

const keyring = new Keyring({ type: 'ethereum' });

// Import from Mnemonic
const mnemonic =
  'fantasy essence ordinary warfare eagle tortoise priority prepare ethics brave wide destroy';
const derivationPath = "m/44'/60'/0'/0/0";
console.log(`Mnemonic: ${mnemonic}`);
console.log(`Derivation Path: ${derivationPath}`);

// Extract address from mnemonic
const newPair = keyring.addFromUri(`${mnemonic}/${derivationPath}`);
console.log(`Derived Address from Mnemonic: ${newPair.address}`);
```

Not specifying the derivation path returns `0x6392417A199C347Bad3b0454dB122405c8a8DAd6`
While specifying it returns the expected address `0x78C9c3E21d94ffc43ef7039038F4D8D807576EdC`
Why is the derivation path needed? When creating the keyring instance I'm specifying the type as `ethereum`, should not this be enough?

On a separate note, I tried deriving the private key from the mnemonic using `mnemonicToLegacySeed` and I don't get the expected private key still. 

```
// Extract private key from mnemonic
const privateKey = u8aToHex(mnemonicToLegacySeed(mnemonic));
console.log(`Derived Private Key from Mnemonic: ${privateKey}`);

const otherPair = await keyring.addFromUri(privateKey);
console.log(`Derived Address from Private Key: ${otherPair.address}`);
```

**Comment by jacogr** [comment]
No. Ethereum has an own path structure, 60‘/… etc. These differ by wallet. 

The library approach here is aligned with Substrate, Ethereum is a guest on it and therefore does not impose any additional rules.

**Comment by albertov19** [comment]
OK so just in case this is useful for anybody else, the following code works. It will return a correctly derived address (using `m/44/60/0/0/index`), it will log also the private key and the corresponding address of the private key (matching the previous one): 

```
// Import Ethereum Account from Private Key
import Keyring from '@polkadot/keyring';
import { u8aToHex } from '@polkadot/util';
import { mnemonicToLegacySeed, hdEthereum } from '@polkadot/util-crypto';

const keyring = new Keyring({ type: 'ethereum' });

// Import from Mnemonic
const mnemonic =
  'fantasy essence ordinary warfare eagle tortoise priority prepare ethics brave wide destroy';
// Define index of the derivation path and the derivation path
const index = 1;
const derivationPath = "m/44'/60'/0'/0/" + index;
console.log(`Mnemonic: ${mnemonic}`);
console.log(`Derivation Path: ${derivationPath}`);

// Extract address from mnemonic
const newPair = keyring.addFromUri(`${mnemonic}/${derivationPath}`);
console.log(`Derived Address from Mnemonic: ${newPair.address}`);

// Extract private key from mnemonic
const privateKey = u8aToHex(
  hdEthereum(mnemonicToLegacySeed(mnemonic, '', false, 64), derivationPath).secretKey
);
console.log(`Derived Private Key from Mnemonic: ${privateKey}`);

// Extract address from private key
const otherPair = await keyring.addFromUri(privateKey);
console.log(`Derived Address from Private Key: ${otherPair.address}`);
```
