### ISSUE TITLE
Issue during compilation

### ISSUE THREAD

**Issue by 4skinSkywalker** [polkadot-js/common#1123]
![image](https://user-images.githubusercontent.com/17194393/135727287-d6cf1191-e71e-44d8-a003-3a6a29daf3b2.png)

How do I solve this?
Thanks

**Comment by 4skinSkywalker** [comment]
I've solved this by commenting the lines below:
![image](https://user-images.githubusercontent.com/17194393/135729213-60b61987-0885-49ec-b7e3-67ca755a6bff.png)

Is my TypeScript version the problems?

**Comment by jacogr** [comment]
See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html

**Comment by 4skinSkywalker** [comment]
> See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html & https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html

This has helped me. But I couldn't update TypeScript to 4.1 due to Angular, I had to painfully migrate it 2 versions up in order to get upgrade TypeScript to the version that could make @Polkadot/{{you name it}} to work.

Thanks!
