### ISSUE TITLE
Usage in a non-ESM project

### ISSUE THREAD

**Issue by faustbrian** [polkadot-js/common#1197]
This issue is about basically the same issue as https://github.com/bitcoinjs/tiny-secp256k1/issues/62. Going full ESM this early on after it being stabilised means that a lot of tooling hasn't caught up yet which means unless you use ESM in your own toolchain it'll be a pain to use the latest version of the packages in this repository as they have been declared as modules through `package.json` which will cause a lot of tools to throw errors and refuse to load them.

```
/home/runner/work/sdk/sdk/common/temp/node_modules/.pnpm/@polkadot/util@7.8.2/node_modules/@polkadot/util/index.js:3
    import "./detectPackage.js";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { IoC, Services } from "@payvo/sdk";
    > 2 | import { u8aToHex } from "@polkadot/util";
        | ^
      3 | import { mnemonicToMiniSecret, naclKeypairFromSeed } from "@polkadot/util-crypto";
```

Works fine with v6 of all packages but with v7 it starts to fail without using the `--experimental-modules` flag.

**Comment by jacogr** [comment]
There is ESM & CJS exposed, it is not ESM only. Therefore it works in both environments. There is a caveat, it requires node >= 14 (as per the engines field)

**Comment by faustbrian** [comment]
The above issue is encountered on 14.18 and 16.13 when running tests with jest while with the v6 releases the issue is not encountered.

**Comment by jacogr** [comment]
Jest has various issues, nothing that can be done here. You can adjust the transform ignores for Jest to get around it. 

```js
transformIgnorePatterns: [
    '/node_modules/(?!@polkadot|@babel/runtime/helpers/esm/)'
  ]
```

**Comment by faustbrian** [comment]
Thanks, will give that a shot. Seems to need a more complex expression when using pnpm.
