### ISSUE TITLE
React Native (Android) Syntax Error 6.9.2

### ISSUE THREAD

**Issue by Kiruse** [polkadot-js/common#1253]
## What Happens
A `[SyntaxError: No identifiers allowed directly after numeric literal]` occurs without stack trace upon importing API library.

## Expected Behavior
Library imports without error.

## Steps to Reproduce
Create basic & empty app using:

```
$ yarn create react-native-app
```

Then, prepare shims:

```
$ yarn add babel-plugin-module-resolver buffer events crypto-browserify stream-browserify
```

Modify `babel.config.js` to add shims:

```javascript
module.exports = function(api) {
  api.cache(false);
  return {
    presets: ['expo'],
    plugins: [
      'react-native-reanimated/plugin',
      ['module-resolver', {
        root: ['.'],
        alias: {
          'crypto': 'crypto-browserify',
          'stream': 'stream-browserify',
        }
      }],
    ],
  };
};
```

Finally, `import { ApiPromise } from '@polkadot/api'` in `App.js` & run `yarn android`. RN's Metro fails to bundle with given Syntax Error.

## Note
This error does not occur in API version 6.0.5. Due to the size of the monorepo it is hard to pinpoint the exact cause.

**Comment by jacogr** [comment]
Closing as duplicate (although this one was logged first) of https://github.com/polkadot-js/common/issues/1245 (which has tracking and replication information)
