### ISSUE TITLE
BigInt and react-native

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/common#1262]
Here I am, very late to the party, and unable to comment [in the related PR](https://github.com/polkadot-js/common/pull/1188), sorry about that.

I bumped the `@polkadot` deps from Stylo and faced a `ReferenceError: Can't find variable: BigInt`.
I used a shim as stated here https://github.com/facebook/react-native/issues/28492#issuecomment-824698934 but as you expected, this doesn't do the trick.

I'm now facing `Error: Invalid integer: 0x428a2f98d728a0000000000000000000000`
I'm not sure where to go, or what to try from here.

I'm using
```js
    "@polkadot/api": "^6.10.3",
    "@polkadot/reactnative-identicon": "^0.87.2",
    "@polkadot/util": "^8.0.4",
    "@polkadot/util-crypto": "^8.0.4",
```

**Comment by jacogr** [comment]
On the first, do you have a specific line number? So, in all cases it tried to do this -

https://github.com/polkadot-js/common/blob/master/packages/util/src/bi/consts.ts#L10-L18

**Comment by jacogr** [comment]
Try 8.0.5 (no shims) - there was a single case missed where it tried to top-level access BigInt. If there are more (I did search for `BigInt`, ensuring they are wrapped around detection, please log with a stack... if available...)

**Comment by Tbaut** [comment]
Thanks for the swift reply. I removed the shim and bumped all the `@polkadot` deps again.
I don't have any line indication unfortunately and get:
```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 ERROR  ReferenceError: Can't find variable: BigInt
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

```

beside a warning that `@polkadot/util` has multiple versions (8.0.5 and 8.0.4 from `@polkadot/wasm-crypto`)

Now running with 
```js
    "@polkadot/api": "^6.10.3",
    "@polkadot/reactnative-identicon": "^0.87.3",
    "@polkadot/util": "^8.0.5",
    "@polkadot/util-crypto": "^8.0.5",
```

I'll dig through the bundles JS if that can help.

**Comment by jacogr** [comment]
If using yarn, just add the latest versions and f the util/util-crypto to resolutions.

**Comment by Tbaut** [comment]
I've used
```js
  "resolutions": {
    "@polkadot/util": "8.0.5"
  }
```

The warning is gone, but I still get the `ERROR  ReferenceError: Can't find variable: BigInt`.
I dug though the js bundle (it's `android/app/src/main/assets/index.android.bundle`) and there are only a couple occurrences:
```js
 function printBasicValue(val, printFunctionName, escapeRegex, escapeString) {
 //...
  if (typeOf === 'bigint') {
    return printBigInt(val);
  }
}
//...
function printBigInt(val) {
  return String("".concat(val, "n"));
}
```
The error is fired before the bundle actually runs.

**Comment by jacogr** [comment]
I'll need to try again to get my RN env setup, been spending a couple of hours and no luck thus far.

So there are 2 ways it is used (simplified, i.e. this is basically exact code) and both should protect against not having `BigInt` at all -

```js
const _n = typeof BigInt !== 'undefined' ? BigInt : () => Number.NaN;

const a = _n(1);
```

and then something like the following -

```js
function a (x) {
  return Bigint(x);
}

function b (x) {
  return Number(x);
}

const c = typeof BigInt === 'undefined'
  ? b(1)
   : a(1);
 ```
 
 So would like to check both forms, since it is the only way it does get accessed.

**Comment by lrxiang222** [comment]
https://github.com/facebook/react-native/issues/28492#issuecomment-824698934

**Comment by jacogr** [comment]
@Tbaut can you please try this (accessing via the global variable instead of directly) -

```
"resolutions": {
  "@polkadot/util": "8.0.6-7",
  "@polkadot/util-crypto": "8.0.6-7"
}
```

It is basically a hail-mary with nowhere using `BigInt`, rather `global.BigInt` (obviously detected for usage, as above)  to see if that makes any difference.

**Comment by Tbaut** [comment]
Thanks, I tried the above, after `yarn add @polkadot/util@8.0.6-7 @polkadot/util-crypto@8.0.6-7`, made sure to clean and reinstall all deps/bundles. but it yields the same error unfortunately

**Comment by jacogr** [comment]
I seem to have missed an instanceof check in the linked PR... so, if you are willing to bear with me, have another version (soon) to check. After that, well, will take the nuclear approach and use an `x-*` package to stub it out completely in react-native.

Will be back in 5... (normally I can and do check, but like I said, have no spent 6+ hrs trying to get RN setup on my new machine and, well, not there...)

**Comment by jacogr** [comment]
@Tbaut maybe ...

```
"resolutions": {
  "@polkadot/util": "8.0.6-8",
  "@polkadot/util-crypto": "8.0.6-8"
}
```

After that, well, really confused as to what it deems as `BigInt`, so the nuclear option with an explicit empty for the environment has a PR...

**Comment by Tbaut** [comment]
Ooooh I'm bringing good news, 8.0.6-8 is working well! Thank you so much for the thorough hunt

**Comment by lrxiang222** [comment]
> @Tbaut maybe it was the instanceof check (they can be problematic)...
> 
> ```
> "resolutions": {
>   "@polkadot/util": "8.0.6-8",
>   "@polkadot/util-crypto": "8.0.6-8"
> }
> ```
> 
> After that, well, really confused as to what it deems as `BigInt`, so the nuclear option with an explicit empty for the RN environment has a PR...

good nice ！Thank you very much, the current opinion on this issue has been resolved。
