### ISSUE TITLE
Unexpected token: name (n) in file node_modules\@polkadot\util\bi\sqrt.js

### ISSUE THREAD

**Issue by lrxiang222** [polkadot-js/common#1270]
const nodeLibs = require("node-libs-react-native");
nodeLibs.bs58 = require.resolve("bs58");
nodeLibs.vm = require.resolve("vm-browserify");

plugins: ['@babel/plugin-proposal-numeric-separator'],

"react": "16.13.1",
"react-native": "0.63.4",
"@polkadot/keyring": "7.9.2",

gradlew app:assembleRelease

**Comment by jacogr** [comment]
See https://github.com/polkadot-js/common/issues/1262
