### ISSUE TITLE
Injector signature cannot be verified

### ISSUE THREAD

**Issue by savudani8** [polkadot-js/common#1309]
I followed the example [here](https://polkadot.js.org/docs/extension/cookbook#sign-a-message):
```
    const injected = await web3FromSource(source as string);
    const signer = injected.signer;
    if (signer.signRaw) {
      const signerResult = await signer.signRaw({
        address: address,
        data: stringToHex(message),
        type: 'bytes'
      });
    }
```

And then used the same account (Bob) and data as in the example [here](https://polkadot.js.org/docs/util-crypto/examples/verify-signature). The result of `signatureVerify(...).isValid` was `false` however.

I couldn't find any tests for both signing and validating with `signRaw`. Maybe there's an alternative to `signatureVerify()` for `signRaw` signatures?

**Comment by jacogr** [comment]
The extension warps the data before signing - however signatureVerify does check for wrapping and tries both wrapped and unwrapped, see https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/signature/verify.ts#L103

**Comment by savudani8** [comment]
Thanks for this! I'll try when I get a chance, until then I'll close the issue
