### ISSUE TITLE
Encryption/Decryption not working with sr25519 keypair

### ISSUE THREAD

**Issue by LaurentTrk** [polkadot-js/common#1314]
Hi all !
This issue is the continuation of the closed #1124 about the support of sr25519 keypair for the [Encryption/Decryption feature](https://github.com/polkadot-js/common/pull/1070).     

After several tests, I cannot get it work, as the `ed2curve.convertPublicKey` used to convert the public key does not work for sr25519 public key.  

The [Ristretto decoding](https://ristretto.group/formulas/decoding.html) of the public key used in [Schnorrkel](https://github.com/w3f/schnorrkel) is not the same as in ed25519.

I managed to make encryption/decryption between 2 sr22519 keypairs using [Ristretto255.js](https://github.com/novifinancial/ristretto255-js), but I can't do it between one ed25519 and one sr25519.

**Could anyone help me ?**

Thanks !

**Comment by LaurentTrk** [comment]
Thanks @jacogr for your reply !  
I don't know what to think about it...

This issue is closely related to [this feature on the extension](https://github.com/polkadot-js/extension/issues/928)(which will be obsolete if this one does not work), and I think it was the plan of @RoyTimes when he first worked on this encryption feature.

**Comment by RoyTimes** [comment]
@LaurentTrk @jacogr Let me look into it. I thought such case is covered with the original tests? I can change the code so that it appends the 32 bytes Curve25519 public key of the sender to the beginning of the message.

**Comment by LaurentTrk** [comment]
Thanks @RoyTimes !  
Yes, `sr25519` tests seems covered, but it appears that coming from an `ed25519` and convert it to `sr255159` (the way it's done in the tests) works, whereas using a native `sr25519` does not.

The test code I am using:
```javascript
const keyring = new Keyring();

const senderPair = keyring.createFromUri(mnemonicGenerate(), { name: 'first pair' }, 'sr25519');
const receiverPair = keyring.createFromUri(mnemonicGenerate(), { name: 'second pair' }, 'sr25519');

const message = stringToU8a('This is a test.');
const encryptedMessage = senderPair.encryptMessage(message, receiverPair.publicKey);
const decryptedMessage = receiverPair.decryptMessage(encryptedMessage, senderPair.publicKey);

const isMatch = u8aToString(message) === u8aToString(decryptedMessage);

// Verify that the decrypted message matches the original message
console.log(`Does the decrypted message match the original message? ${isMatch}`);
```

Under the hood, the conversion of the `sr25519` public key with the `ed2curve.convertPublicKey()` function fails (make sense as the [ed2curve](https://github.com/dchest/ed2curve-js) is designed to handle `ed25519` keypairs.

Thanks again for your help.

**Comment by RoyTimes** [comment]
@LaurentTrk @jacogr I have posted a fix.

**Comment by revick** [comment]
Thanks - ran into issues with this today, looking forward to this fix.

**Comment by amany9000** [comment]
@jacogr @LaurentTrk I'm still facing this issue with sr25519, for some keys encryptMessage() works, for others it errors with `Unable to convert publicKey to ed25519` from  convertPublicKeyToCurve25519().

**Comment by jacogr** [comment]
This functionality will probably be removed completely. There is no sane way of doing this at all. (Where “sane” refers to no having to share other keys out of band)

**Comment by LaurentTrk** [comment]
Hi @amany9000 
As @jacogr mentionned, this will not be fixed in the Polkadot JS library, nor the extension.

If you plan to use this feature from a wallet, I am aware that the Talisman Wallet team has added support for encryption/decryption recently ([from the version v1.10.0](https://docs.talisman.xyz/talisman/prepare-for-your-journey/wallet-release-notes#v1.10.0-november-4th-2022)).

**Comment by amany9000** [comment]
Thank you for the confirmation @jacogr .
