### ISSUE TITLE
TypeError: Conversion from 'BigInt' to 'number' is not allowed.

### ISSUE THREAD

**Issue by binkerxbc** [polkadot-js/common#1330]
IOS14.4 or later. This error has occurred.
 I just import the library and I get this error. The program crashed.
 But in ios 13.7 it works 

   "@polkadot/api-6": "npm:@polkadot/api@^6.12.1",
   "react-native": "0.63.4",
    "react": "16.13.1",

**Comment by jacogr** [comment]
Duplicate of https://github.com/polkadot-js/common/issues/1321
