### ISSUE TITLE
Can I search the API?

### ISSUE THREAD

**Issue by btfdip** [polkadot-js/common#1357]
https://polkadot.js.org/docs/api/start/api.tx

It's really stupid there is no search function especially for devs. So what are this website designed for? for normal users?

**Comment by btfdip** [comment]
off-topic, dot's UI design is really shitty, for customers, it's too techy for them to understand, for developers, it's not convenient to use(search API)

**Comment by jacogr** [comment]
Closing as duplicate, there is a long-running issue logged in the docs repo. As always PRs welcome..
