### ISSUE TITLE
`main` module field could not be resolved for @polkadot/util

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/common#1384]
I'm running into an issue recently with React Native, than I can't explain. 

> Error: While trying to resolve module `@polkadot/util` from file `/home/thib/Github/stylo-app/stylo/node_modules/@polkadot/types/detectPackage.js`, the package `/home/thib/Github/stylo-app/stylo/node_modules/@polkadot/types/node_modules/@polkadot/util/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/home/thib/Github/stylo-app/stylo/node_modules/@polkadot/types/node_modules/@polkadot/util/index.cjs`. Indeed, none of these files exist:

I read in the changelogs, that the types package has been split into different packages for newer versions, but I'm still using older versions:
```
    "@polkadot/api": "^6.12.1",
    "@polkadot/reactnative-identicon": "^0.87.5",
    "@polkadot/util": "8.1.2",
    "@polkadot/util-crypto": "8.1.2"
```

**Comment by jacogr** [comment]
The index.cjs file is indeed there. 

The fact that the util is inside node_modules/api/node_modules/… does indicate that multiples are installed.

**Comment by Tbaut** [comment]
I really have no idea how this came and went. The issue has disappeared, It's part of React Native magic.. when I checked, the `.cjs` was not present though.
