### ISSUE TITLE
Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.

### ISSUE THREAD

**Issue by ThreeAndTwo** [polkadot-js/common#1385]
When I use Keystore to call sign, the following error will be triggered. How should I repair it？

This is the whole source.
` const json = JSON.parse('{"encoded":"xxx","encoding":{"content":["pkcs8","sr25519"],"type":["scrypt","xsalsa20-poly1305"],"version":"3"},"address":"5XXXX","meta":{"whenCreated":1642412357194,"name":"test","genesisHash":"0x9"}}')
    const decodedJson = decodePair('1', base64Decode(json.encoded), json.encoding.type);
    const keyring = new Keyring({ ss58Format: 0 });

    let account = keyring.createFromPair(decodedJson, json.meta,'sr25519');
    console.log("account:", account)
    console.log("address:", account.address)

     console.log("account index %d", i)
     // const account = await getAccount(mnemonic, i, AccountType.SR25519, 0)

     const timestamp = new Date().toISOString()
     console.log("timestamp:", timestamp)

        const payload = {
            action: "Withdraw",
            amount: "50000000000",
            timestamp: timestamp,
        }

        const plStr = JSON.stringify(payload)
        const message = stringToU8a(plStr)
        const signature = account.sign(message)
        console.log("signature:", u8aToHex(signature))`  // Error:  The WASM interface has not been initialized.

**Comment by jacogr** [comment]
The error message tells you exactly what to do. Before working with `sr25519` you need to have the WASM interface initialised.

So as per the imports from the actual error you pasted here -

```js
import { cryptoWaitReady } from '@polkadot/util-crypto';

await cryptoWaitReady();

...

const signature = account.sign(message)
console.log("signature:", u8aToHex(signature))`
```

**Comment by ThreeAndTwo** [comment]
thx, it worked!
