### ISSUE TITLE
Error: Expected a seed matching 32 bytes, found 0

### ISSUE THREAD

**Issue by akshitv1** [polkadot-js/common#1395]
I am calling function : keyring.addFromMnemonic(mnemonic);
Getting this error : 
Error: Expected a seed matching 32 bytes, found 0
    at assert (/node_modules/@polkadot/util/assert.cjs:37:11)
    at sr25519PairFromSeed (/node_modules/@polkadot/util-crypto/sr25519/pair/fromSeed.cjs:23:20)
v7.3.1 and v7.6.1
Please look into it, it was working fine around 3 weeks back !!
Let me know if u need more info.

**Comment by jacogr** [comment]
See https://github.com/jacogr/keyring-test-1395 for correct usage

**Comment by akshitv1** [comment]
Hi @jacogr 
I was tracing the flow of the functions and came to this function : ext_bip39_to_mini_secret defined in @polkadot/wasm-crypto/types.d.ts. This function is however not declared anywhere, by that i mean, types.cjs and types.js is empty in these folders. 
The reason i reached to this point was because, keyring.cjs file which has function createFromUri, is not able to define the constant called seed. 
And therefor the error mentioned above is coming

**Comment by jacogr** [comment]
types.js and types.cjs is meant to be empty - the source only contains type & interface exports, see https://github.com/polkadot-js/wasm/blob/master/packages/wasm-crypto/src/types.ts

**Comment by jacogr** [comment]
Look at the repoduction posted above - correct, no errors. Comp[are that to your code.

**Comment by akshitv1** [comment]
> Look at the repoduction posted above - correct, no errors. Compare that to your code.

**Comment by akshitv1** [comment]
> Look at the repoduction posted above - correct, no errors. Compare that to your code.

Hi @jacogr yes it worked when i run from the repo given above, but when i install same version of @polkadot/keyring, in my project, with node -v 14.17.5, it throws the above mentioned error. 
I dont think that i have different packages. 
Let me know if u could help me with this.
