### ISSUE TITLE
Attempted import error: 'TextDecoder' is not exported from '@polkadot/x-textdecoder'.

### ISSUE THREAD

**Issue by hobbydev71** [polkadot-js/common#1450]
I installed following polkadot packages.
```
"@polkadot/api": "6.10.1",
    "@polkadot/extension-dapp": "0.41.1",
    "@polkadot/hw-ledger": "8.2.2",
    "@polkadot/util-crypto": "8.0.2",
```
When run the "yarn start", I got this error.
./node_modules/@polkadot/util/u8a/toString.js
Attempted import error: 'TextDecoder' is not exported from '@polkadot/x-textdecoder'.

How can I fix that?

**Comment by jacogr** [comment]
It is exported, see https://github.com/polkadot-js/common/blob/36d8f6c922c72930a0763c4ef212ab3c1fa755a3/packages/x-textdecoder/src/browser.ts#L10

You do seem to be mixing version ranges along the way, i.e. `8.0.2` and `8.2.2` (this will cause warnings when running)

**Comment by hobbydev71** [comment]
I re-tired after fixed the version as following.
```
"@polkadot/api": "6.10.1",
"@polkadot/extension-dapp": "0.41.1",
"@polkadot/hw-ledger": "8.2.2",
"@polkadot/util-crypto": "8.2.2",
```
but still get same issue.

**Comment by abdulhaseeb13mar** [comment]
getting same error:
./node_modules/@polkadot/util/u8a/toString.js
Attempted import error: 'TextDecoder' is not exported from '@polkadot/x-textdecoder'.

**Comment by jpangelle** [comment]
Also getting this issue. Ejected `create-react-app` on `react-scripts@4.0.3` so I am running `webpack@v4.44.2`.

All of my `@polkadot` packages are on the latest versions:

```
"@polkadot/api": "7.15.1",
"@polkadot/extension-dapp": "0.42.10",
"@polkadot/keyring": "8.7.1",
"@polkadot/networks": "8.7.1",
"@polkadot/typegen": "^7.15.1",
"@polkadot/types": "7.15.1",
"@polkadot/ui-keyring": "1.4.1",
"@polkadot/ui-settings": "1.4.1",
"@polkadot/util": "8.7.1",
"@polkadot/util-crypto": "8.7.1",
```

**Comment by jpangelle** [comment]
I ended up fixing this by abandoning `create-react-app` and therefore `webpack`. I migrated to [`vite`](https://vitejs.dev/guide/build.html) using this [guide](https://javascript.plainenglish.io/migrating-a-create-react-app-cra-application-to-vite-788b13243b5a?gi=6c9c59428868). It only took like 20 minutes to migrate over and everything just worked.
