### ISSUE TITLE
React-Native - WASM interface has not been initialized

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/common#1456]
spliting from https://github.com/polkadot-js/common/issues/1440

I pushed the code here
https://github.com/stylo-app/stylo/compare/wasm-not-ready?expand=1

Doing as you advise, in the `index.js` and having an `await cryptoWaitReady().catch(console.log)` before any use of `util-crypto` function. I get no error logged from the catch it seems

```
 BUNDLE  ./index.android.js 

 WARN  Require cycle: node_modules/react-native-crypto/index.js -> node_modules/react-native-randombytes/index.js -> node_modules/sjcl/sjcl.js -> node_modules/react-native-crypto/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 ERROR  Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

```

**Comment by jacogr** [comment]
Where does the crash occur? Which file?

**Comment by Tbaut** [comment]
It occurs right at the start after the bundle was loaded, the app crashes right away before showing anything. I have no other stack trace or log unfortunately, the screen remains blank.

**Comment by jacogr** [comment]
Very weird that that this doesn't happen at all in the test app. I have some ideas, this specifically - https://github.com/polkadot-js/ui/pull/632

This line actually seems suspect - https://github.com/polkadot-js/ui/pull/632/files#diff-20533d323fc4b95039d17ffe2c8e09a4a06a4cedc47dc02c11b6025f58f04cf0L25

**Comment by Tbaut** [comment]
Something I did not mention and may be related, in all my tests with test projects, the identicon did not crash, but did not show up properly either, just a grey circle, no small colored circles inside.

**Comment by jacogr** [comment]
Could I ask you to check the common 9.0.1 versions alongside the ui 2.0.1 versions?

(The api has not been updated yet, so may have dragons... that will only go tomorrow)

**Comment by Tbaut** [comment]
No problem at all, RN is a pain, and I'm very much uneasy with it either :D

Stylo is not crashing at launch with the following (deps and resolutions):
```
  "resolutions": {
    "@polkadot/api": "^7.15.1",
    "@polkadot/reactnative-identicon": "^2.0.1",
    "@polkadot/util": "^9.0.1",
    "@polkadot/util-crypto": "^9.0.1",
    "@polkadot/wasm-crypto": "^6.0.1"
  }
```

However, I had some warnings (unrelated to polkadot afaik) and errors thrown at me (with call stack!), at the launch, pasting everything here, one if them being the "WebAssembly is not available in your environment ":
```
WARN  Require cycle: node_modules/react-native-crypto/index.js -> node_modules/react-native-randombytes/index.js -> node_modules/sjcl/sjcl.js -> node_modules/react-native-crypto/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```
```
 ERROR  FATAL: Unable to initialize @polkadot/wasm-crypto:: WebAssembly is not available in your environment 
AccountsContextProvider@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.styloapp&modulesOnly=false&runModule=true:141000:24
NetworksContextProvider@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.styloapp&modulesOnly=false&runModule=true:193928:24
RNCSafeAreaProvider
SafeAreaProvider@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.styloapp&modulesOnly=false&runModule=true:230462:24
App
RCTView
View
RCTView
View
AppContainer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.styloapp&modulesOnly=false&runModule=true:78488:36
stylo-app(RootComponent)@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.styloapp&modulesOnly=false&runModule=true:85373:28
```

When using the app, the identicons are now all grey (like in the test app see screenshot below) and I get an error in the console
> [Error: Decoding 5FNyDvUe5eFpZRMet48MNyckFJ69UGaLBrPqCjiSEhSDQaLn: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.]

![image](https://user-images.githubusercontent.com/33178835/162587228-00da759b-8fd1-4760-b1ad-9d2e2173d0ba.png)

Digging in my code, this is thrown when calling this function [here](https://github.com/stylo-app/stylo/blob/wasm-not-ready/src/context/AccountsContext.tsx#L67), and there's an `await cryptoWaitReady()` before any of the 2 `decodeAddress` present in this function are called.

**Comment by jacogr** [comment]
Ok, the non-crash is good. So the init in this case doesn't work - I really wonder why? In my test app it certainly did, i.e. blake2 was my actual testcase.

**Comment by ToufeeqP** [comment]
Hi, Any update on this issue? I am also facing this issue but interestingly only in the Android, on iOS it works fine

**Comment by tzechuen** [comment]
It was working for me on the iOS simulator, but not on an actual device.

It started working for me when I used the beta version of `@polkadot/wasm-crypto`: 

I added this in my package.json:

`    "@polkadot/wasm-crypto": "6.0.2-9",
`

**Comment by jacogr** [comment]
Excellent news. That was certainly meant to address the issue. Will release it over the weekend.

**Comment by tzechuen** [comment]
Yup great work with the fix for iOS, but strange I am facing this issue again when running on Android. Have also tried importing `initOnlyAsm`. I tried adding `cryptoWaitReady` in `index.js` but the code was not even reached so I think it crashed at the bundling stage.

Not sure what else I could try here...

**Comment by jacogr** [comment]
What error log does it show to you?

**Comment by tzechuen** [comment]
hey @jacogr sorry for late reply, here is what was on my error log:

` ERROR  Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
`

It looks similar to the one @Tbaut have above. Thanks!

**Comment by jacogr** [comment]
9.2.1 has the changes for the RN-default-to-asm.js changes above, i.e. pulls in the wasm repo PR. Additionally, it re-introduced the top-level `cryptoWaitReady()` that was present in earlier versions, i.e. automatic waiting for that. 

With the 2 above, it bring it functionally on-par, or at least follows the same process of what _did_ work in the past on RN. If it solves all the issues here remains to be seen.

**Comment by Tbaut** [comment]
Thanks a lot Jaco, I tested it after a bump and the error is gone. I've others that may be related to my code. Also I saw the numeric literal one again cf https://github.com/polkadot-js/common/issues/1440 , I'll investigate further in the next days, but for now this issue is solved :)

**Comment by Tbaut** [comment]
I can confirm, it was my code. I'm now able to build Stylo with all the latest polkadot deps, the identicon also work well again :tada:
