### ISSUE TITLE
Support for storage value proof verification

### ISSUE THREAD

**Issue by ERussel** [polkadot-js/common#1481]
polkadot/api has a function to retrieve a [proof](https://polkadot.js.org/docs/substrate/rpc/#getreadproofkeys-vecstoragekey-at-blockhash-readproof) for storage value given corresponding key. But is there a library that allows to verify received proof against Merkle root?

Our research shows that we need proper implementation of the trie-db. We tried to use one from polkadot/common 1.8.1 but looks like it is outdated (for example, NibbledBrachNode type is missing for Trie node). The only option we see now is to port Rust implementation of the proof verification that looks very complicated but may be there is an easier way?

**Comment by jacogr** [comment]
The trie-hash is indeed very outdated, it has not kept up with the latest changes. (It has moved code locations, here is the PR with the latest code that was in common https://github.com/polkadot-js/client/pull/250/files). I'm assuming the trie-hash should actually be sufficient, but yes, it is outdated as opposed to Rust master.

I cannot think of another way. I guess without porting if the trie-hash can be compiled to WASM, it would be the best solution from a compatibility perspective.
