### ISSUE TITLE
[React Native] import.meta is only valid inside modules error when importing initOnlyAsm 

### ISSUE THREAD

**Issue by tzechuen** [polkadot-js/common#1509]
After updating to the latest dependencies:

```
    "@polkadot/api": "^8.6.1",
    "@polkadot/keyring": "^9.3.1",
    "@polkadot/util": "^9.3.1",
    "@polkadot/util-crypto": "^9.3.1",
    "@polkadot/wasm-crypto": "^6.1.1",
```

and adding `import '@polkadot/wasm-crypto/initOnlyAsm';` at the top of `index.js` file, I'm getting `import.meta is only valid inside modules` error for both iOS and Android.

![Simulator Screen Shot - iPhone 13 - 2022-05-30 at 15 22 22](https://user-images.githubusercontent.com/4160142/170939865-d11f4d4a-0ed9-45e6-9f62-0e61bc3e78ed.png)

**Comment by jacogr** [comment]
You don't need the import explicitly when using RN since the `wasm-crypto` 6.1.1 release. 

However, if you wish to be explicit, since RN ignores the import maps (introduced as a standard in Node 12.x), rather point it explicitly (this is not needed on any recent bundlers supporting export maps) to -

`import '@polkadot/wasm-crypto/cjs/initOnlyAsm';`

**Comment by tzechuen** [comment]
hey @jacogr thanks for getting back so quickly. After updating to the 6.1.1 release, I still wasn't able to run it on Android. I am still getting the WASM errors:

```
 ERROR  Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

The idea to try `initOnlyAsm` came from checking out Stylo's codebase as the devs seem to be able to run the latest `wasm-crypto` release on Android without issues.

I tried `import '@polkadot/wasm-crypto/cjs/initOnlyAsm';` and the `import.meta` error is gone, however the same WASM errors above have re-appeared. Strangely these errors only appear on Android, but works perfectly fine on iOS.

**Comment by Tbaut** [comment]
I had the `import.meta` issue as well in the past indeed, from previous conversation and as Jaco said, this is linked to the bundler. It seems that newer releases using React 18 use webpack 5, so I bumped `react` and `react-native`, and I haven't had that issue since then. Currently using:
```
    "react": "^18.1.0",
    "react-native": "0.68.2",
```

**Comment by Tbaut** [comment]
I have the same issue with the RN-Test-Project too unfortunately, and I'm not able to pin point where this problem comes from either. I am still able to build Stylo with the latest polkadot-js dependencies so I think it must come from the build params.

**Comment by vietnamese-chowder** [comment]
I'm having the same issue, updating react and react-native didn't help

**Comment by Gzernov** [comment]
We have the same issue

**Comment by chezhe** [comment]
> hey @jacogr thanks for getting back so quickly. After updating to the 6.1.1 release, I still wasn't able to run it on Android. I am still getting the WASM errors:
> 
> ```
>  ERROR  Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
>  ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
>       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
>  ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
>       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
> ```
> 
> The idea to try `initOnlyAsm` came from checking out Stylo's codebase as the devs seem to be able to run the latest `wasm-crypto` release on Android without issues.
> 
> I tried `import '@polkadot/wasm-crypto/cjs/initOnlyAsm';` and the `import.meta` error is gone, however the same WASM errors above have re-appeared. Strangely these errors only appear on Android, but works perfectly fine on iOS.

Is this problem solved? I got same issue.

**Comment by tzechuen** [comment]
Hey all, I have discovered a workaround to get it working on Android. Basically, from my findings it seems that the WASM errors get thrown even if you insert Platform checking logic to prevent code execution i.e. doing `if (Platform.OS === 'android') return;` will still cause the WASM errors to get thrown, so I suspect it might have something to do with the bundling stages but I'm not entirely sure...

Today I discovered the workaround by chance, I remembered reading somewhere there was a way to do lazy imports so I did a quick research, tested and landed on this solution that worked for me.

At the top of the file you can have something like this:

```
import type { Keyring } from '@polkadot/keyring';
import { cryptoWaitReady } from '@polkadot/util-crypto';

let _Keyring: typeof Keyring | undefined = undefined;

cryptoWaitReady().then(() => {
  import('@polkadot/keyring').then((keyring) => {
    _Keyring = keyring.Keyring;
  });
});
```

Then in the code below:

```      
      if (!_Keyring) {
        throw new Error('No Keyring available');
      }

      const keyring: Keyring = new _Keyring();
```

Then you can now use `Keyring` functions.

This solution might not work properly if you need to use PolkadotJS library within a constructor of a class. For use within a constructor, something like this should work:

```

  constructor() {
    cryptoWaitReady().then(() => {
      import('@polkadot/api').then((api) => {
        const { WsProvider, ApiPromise } = api;
        // Your other code here...
      });
    });
  }
```

If your IDE complains that the lazy imports above are not supported, you just need to add something like `"module": "esnext"` under `"compilerOptions"` inside `tsconfig.json` file (this is if you're using TypeScript).

Also note I did not need to do `initOnlyAsm` as I initially did.

There are probably more elegant solutions but this seems suffice to get PolkadotJS working on Android for now. Please feel free to share if you find a more elegant way for this workaround. Would love to know. Thanks!

**Comment by chezhe** [comment]
I fixed by this way too. Just conditionally import any other files which imported `@polkadot/api`.
