### ISSUE TITLE
Documentation should be built again

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/common#157]
Currently the generation is not available although the docs are there -

https://github.com/polkadot-js/dev/issues/132

**Comment by ltfschoen** [comment]
@jacogr What's your preference for generating API docs, which of the following would you prefer?
1) using typedoc to build docs from ESDoc comments (i.e. PR #135 that has been merged) OR
2) creating nested markdown files (see https://github.com/polkadot-js/common/tree/master/packages/util-keyring/docs) OR
3) adding docs to a Readme file similar to @palanisn's approach https://github.com/palanisn/api/commit/42ca54df1b202888d334ebca6396fea808657d4c in addressing https://github.com/w3f/Web3-collaboration/issues/34

**Comment by jacogr** [comment]
Luke, sorry, only noticed this question now - I would like to keep things consistent. So what we do on the api repo, that is what we should do here.
