### ISSUE TITLE
Please update Nodel chain network name

### ISSUE THREAD

**Issue by jay-infocusp** [polkadot-js/common#1634]
https://github.com/polkadot-js/common/blob/master/packages/networks/src/defaults/genesis.ts#L70 
It should be renamed to 'nodle' instead of 'nodle-para' 

Because, it gets filters out here 
https://github.com/polkadot-js/common/blob/master/packages/networks/src/interfaces.ts#L25
https://github.com/polkadot-js/common/blob/master/packages/networks/src/interfaces.ts#L42

Please update it according to name as per KnownSubstrate : https://github.com/polkadot-js/common/blob/master/packages/networks/src/interfaces.ts#L4 which is 'nodle'

**Comment by jacogr** [comment]
The naming as it stands was contributed. The team itself would need to make a PR to adjust.
