### ISSUE TITLE
Why do we need `<Bytes></Bytes>`?

### ISSUE THREAD

**Issue by AurevoirXavier** [polkadot-js/common#1710]
Sorry for asking a question here.

But this is really really tricky. Why do we need that?

And is there a way to sign the message without the `<Bytes></Bytes>`.

I don't want to put this in my Rust pallet's verification function. It looks weird.

**Comment by jacogr** [comment]
It was something that was added to the polkadot-js extension to ensure users are not duped into signing any random transaction and then an unscrupulous website using that to submit a transaction. So basically the wrapper turns it into something that cannot be a transaction payload. (It is slightly similar to the few bytes that stuff like Ethereum adds when signing raw data)

TL;DR Raw data signing capabilities are always "slightly" dangerous

**Comment by AurevoirXavier** [comment]
Thanks for your explanation.

For extension, it's good. But as a library, I think there should be a `sign_raw` or `unsafe_sign_raw`.

This `sign_raw` looks not `raw` enough to me.

**Comment by jacogr** [comment]
Sadly, It is not going to change. (If there was a ever a new industry-wide standard for prefixes, it will obviously adapt)
