### ISSUE TITLE
How to recover the secret key from a json file?

### ISSUE THREAD

**Issue by AurevoirXavier** [polkadot-js/common#1759]
I'm sorry to ask a question here.

I tried some searches.

And I found this: https://substrate.stackexchange.com/questions/3284/how-to-get-the-private-key-using-polkadot-js/3286#3286

I want to know how to decode the encoded private key.

We encounter some invalid signature problems with some specials account. And we want to write some unit tests in our rust code. But I don't know how to reproduce the signing in the rust code. I can't create that pair base on the given json file.

Thanks!

**Comment by jacogr** [comment]
You should be able to use this (which is used internally in the keyring) - https://github.com/polkadot-js/common/blob/77c6177c9abe8355a1d8775e25a572122e310ee7/packages/keyring/src/pair/decode.ts#L18

The encoded data and the encoding type is from the json.

**Comment by AurevoirXavier** [comment]
> You should be able to use this (which is used internally in the keyring) -
> 
> https://github.com/polkadot-js/common/blob/77c6177c9abe8355a1d8775e25a572122e310ee7/packages/keyring/src/pair/decode.ts#L18
> 
> The encoded data and the encoding type is from the json.

Thanks!

What's the difference between a seed and a secret key? It looks like I can't use the secret key in Rust code which is 64 in length.

And I found there is a `convertSecretKeyToCurve25519` method. I called this function but got a wrong seed.

**Comment by jacogr** [comment]
With the 64-byte keys, just grab the first 32 bytes. 

(The ed25519 secret keys are weird - it is basically the 32 byte secret + 32 byte public - I guess the libs use it that way for verification)

**Comment by jacogr** [comment]
It has actually be n removed this morning - it was used to convert sr5519 and ed25519 keys to the same base so they can share the encrypted messages. 

… however attempts to “fix “ it didn’t prove to “fix” it. Since it cannot work that way without an offline exchange of secrets, the encrypt functions were removed this morning… after around 12 months of PRs hanging about…
