### ISSUE TITLE
What's the difference between `injector?.signer?.signRaw` in browser and `KeyringPair.sign` in node.js?

### ISSUE THREAD

**Issue by xiyu1984** [polkadot-js/common#1786]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [x] Other

* **What is the current behavior and expected behavior?**

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

## Details

I input the same message `'hello'` to be signed by both two methods. But unfortunately, I got different results.

- The code of using [injector?.signer?.signRaw](https://github.com/xiyu1984/polkadot-web-test/blob/ec1cabebc35c5cd55f021de31f334d87eb03fbb9/lib/onchain.js#L31)  
-  The code of using [KeyringPair.sign](https://github.com/dantenetwork/protocol-stack-for-ink/blob/022ec800b3433637e1ff9ede102d8068356d0c04/test/vvtest.mjs#L93). I use [{type: ethereum}](https://github.com/dantenetwork/protocol-stack-for-ink/blob/022ec800b3433637e1ff9ede102d8068356d0c04/test/ink_base.mjs#L75) to create the keypair.   

 I use `secp256k1` to create the `keypair`, and the hash func is `keccak256`.  I imported the `keypair` into the `polkadot-js` wallet.  

I guess it might be because `injector?.signer?.signRaw()` uses a different elliptic curve or a different hash func? I have not found anywhere to set these parameters when using `injector?.signer?.signRaw()`.  

Is there any suggestions?

**Comment by jacogr** [comment]
Underlying they both use “sign” on the keyring. The differences are -

- sign just signs the data passed - so everything as-is
- signRaw ensures the message is wrapped in “<Bytes>hello</Bytes>” before passing to sign (the u8aWrap function in util)

The wrapping is to ensure the bytes cannot be used for transactions, eg. if a user is duped into signing transaction bytes, the signature won’t be valid for a transaction. 

On the reverse side - no user-specific wrapping is needed for verify in the JS utils (it would determine wrapping automatically)

**Comment by xiyu1984** [comment]
> Underlying they both use “sign” on the keyring. The differences are -
> 
> * sign just signs the data passed - so everything as-is
> * signRaw ensures the message is wrapped in “hello” before passing to sign (the u8aWrap function in util)
> 
> The wrapping is to ensure the bytes cannot be used for transactions, eg. if a user is duped into signing transaction bytes, the signature won’t be valid for a transaction.
> 
> On the reverse side - no user-specific wrapping is needed for verify in the JS utils (it would determine wrapping automatically)

Thanks for your clear explanation, and I think I have got it. It's a similar mechanism to `personal sign` and `sign typed data` in Ethereum.  

The implementation of the [`wrap`](https://github.com/polkadot-js/common/blob/master/packages/util/src/u8a/wrap.ts) makes sense.  

By the way, maybe it will be better that there's a description in the [example](https://polkadot.js.org/docs/extension/cookbook/#sign-a-message).
