### ISSUE TITLE
Expose `Keypair` from util-crypto/src/types.ts in util-crypto/bundle.ts

### ISSUE THREAD

**Issue by RmbRT** [polkadot-js/common#1891]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Package util-crypto exposes `sr25519PairFromSeed`, which returns `Keypair` from `../../types.ts`, but this type itself is never exported, so I cannot refer to it in my code.

* **What is the motivation for changing the behavior?**
I don't want to have to use `any` to store a Keypair.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript 4.8.4
    - [ ] Other

**Comment by jacogr** [comment]
https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/types.ts#L7-L12

Hence -

```js
import type { Keypair } from '@polkadot/util-crypto/types.ts;

const kp: Keypair = ...
```

**Comment by RmbRT** [comment]
That's ugly, though. I think you shouldn't make people rely on the internal file structure of a dependency. That's the whole point of using an `index.ts` or `bundle.ts`. To represent a whole project in a single collection of exported entities, potentially namespaced.
But thanks, I didn't know it was allowed to import individual non-index files from a js/ts dependency.
