### ISSUE TITLE
Can the seed be recovered from the secret key?

### ISSUE THREAD

**Issue by AurevoirXavier** [polkadot-js/common#1899]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

Based on our previous discussion at https://github.com/polkadot-js/common/issues/1759#issuecomment-1468172499, I discovered that obtaining the seed in this manner is incorrect. The initial 32 bytes do not correspond to the seed. After conducting further research, I learned that certain secret keys are derived from the seed, making it impossible to retrieve the seed from the key. Therefore, is it possible to obtain the seed in this context?

**Comment by AurevoirXavier** [comment]
After reviewing the implementation at https://github.com/w3f/schnorrkel, I believe this is not feasible. The term "Seed" refers to what they call a `MiniSecretKey`, while the `SecretKey` is derived from the `MiniSecretKey` using certain hash functions.

**Comment by jacogr** [comment]
Indeed. It is a one-way hashing to get to the other side.
