### ISSUE TITLE
Please provide documentation for the pkcs8 related constants in keyring

### ISSUE THREAD

**Issue by clearloop** [polkadot-js/common#1908]
Documentation requests

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

https://github.com/polkadot-js/common/blob/6971012f4af62f453ba25d83d0ebbfd12eaf5709/packages/keyring/src/pair/defaults.ts#L4-L5

```js
// review: where are these bytes from, what's the exact meaning of them
export const PKCS8_DIVIDER = new Uint8Array([161, 35, 3, 33, 0]);
// review: same
export const PKCS8_HEADER = new Uint8Array([48, 83, 2, 1, 1, 48, 5, 6, 3, 43, 101, 112, 4, 34, 4, 32]);
```

the header and divider here seems not following the private key information syntax defined in [RFC5208-section-5](https://datatracker.ietf.org/doc/html/rfc5208#section-5)

```
PrivateKeyInfo ::= SEQUENCE {
        version                   Version,
        privateKeyAlgorithm       PrivateKeyAlgorithmIdentifier,
        privateKey                PrivateKey,
        attributes           [0]  IMPLICIT Attributes OPTIONAL }

Version ::= INTEGER
PrivateKeyAlgorithmIdentifier ::= AlgorithmIdentifier
PrivateKey ::= OCTET STRING
Attributes ::= SET OF Attribute
```

both encode and decode methods are using these constants without any description, no tests provided, just hardcode bytes level checks 

https://github.com/polkadot-js/common/blob/6971012f4af62f453ba25d83d0ebbfd12eaf5709/packages/keyring/src/pair/encode.ts#L16-L21
https://github.com/polkadot-js/common/blob/6971012f4af62f453ba25d83d0ebbfd12eaf5709/packages/keyring/src/pair/decode.ts#L25-L27

**Comment by jacogr** [comment]
Closed in #1910
