### ISSUE TITLE
Refactor blake2b subdirectory into blake2 outer directory 

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/common#232]
In https://github.com/polkadot-js/common/tree/master/packages/util-crypto/src/blake2, we could get rid of blake2bAsHex and blake2bAsU8a, and instead just use blake2AsHex and blake2AsU8a (but making the bitLength argument optional). Meaning we'd get rid of the blake2 subdirectory (the second subdirectory). Based on discussion with @jacogr we are just using blake2b, not blake2s, so we can get rid of the subdirectory approach 
Not since there is only 2b, can flatten the whole thing.
Assume that the only use of the subdirectory is inside that directory, so it shouldn't be necessary to update other repos, but double check anyway if anything points to blake2/blake2b/*.ts.

So the only thing that we should do that has been suggested i.e. top-level. Instead of this -

https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/blake2/asHex.ts#L19
```
export default function blake2AsHex (data: Uint8Array, bitLength: number = 256): string {
  return blake2bAsHex(data, bitLength);
}
```

We should just do the following, which is basically what's inside the 2b directory
```
export default function blake2AsHex (data: Uint8Array, bitLength: number = 256): string {
  return u8aToHex(
    blake2bAsU8a(data, bitLength)
  );
}
```

Note that in the blake2b subdirectory, the default value for bitLength is 512, whereas the calling functions in the outer directory have a default value of bitLength as 256. We should use the 256 default, since all our hashes are 32 bytes

**Comment by jacogr** [comment]
Closing. We actually have areas where we need blake2 for more than the hash and with the full 512 bits capability.
