### ISSUE TITLE
Substrate has change ss58 check for ed25519

### ISSUE THREAD

**Issue by JKingdom** [polkadot-js/common#406]
related to this issue https://github.com/paritytech/substrate/issues/2332
the ss58 check for generate addr checksum has changed
but this lib not match for this modification.
https://github.com/polkadot-js/common/blob/master/packages/keyring/src/address/encode.ts

hope to fix it soon, thx

**Comment by jacogr** [comment]
The generation of ed25519 vs sr25519 never made a distinction in the encoding on the JS side -

So using this test from substrate https://github.com/paritytech/substrate/pull/2355/files#diff-784e2474b3d9dd4d665165f85f71550eR166 (use raw sees, select ed25519, check address on polkadot.js.org/apps) yields the same address as in the above test, i.e. `5DKUrgFqCPV8iAXx9sjy1nyBygQCeiUYRFWurZGhnrn3HJCA`

The apps UI also (when adding an address) allows the input of a public key and then would convert this hex to an address. So using this from your supplied data `0x00308187439ac204df9e299e1e54a00000000bf348e03dad679737c91871dc53` results in the address `5C4xGQZwoNEM5mdk2U3vJbFZPr6ZKFSiqWnc9JRDcJ3w334p`

**Comment by jacogr** [comment]
Another view, using subkey and doing the following - `cargo run --release -- -e inspect "//Jacob"` yields `5EUXNnW9gShgBSyJR3iQds9qGSBexMH9785vAdKMCdPyA6Ca`

The above UI generates `5EUXNnW9gShgBSyJR3iQds9qGSBexMH9785vAdKMCdPyA6Ca` for the same input.
