### ISSUE TITLE
Opt out debugging log in test mode

### ISSUE THREAD

**Issue by benxgao** [polkadot-js/common#491]
Currently it seems debug mode is forced to be enabled in test env, [code here](https://github.com/polkadot-js/common/blob/master/packages/util/src/logger.ts#L117), but sometimes I want to disable it while running test. Is there any way I could effectively make it?

**Comment by jacogr** [comment]
To “sometimes disable” I generally do -

NODE_ENV=a yarn test 

(Eg  as/when needed to debug)

**Comment by benxgao** [comment]
Do you think it would get `DEBUG` mode working with test environment like: 

```js
// Before:
isDebug = isTest || !!debugList.find((entry): boolean => _type.startsWith(entry));

// After:
isDebug = !!debugList.find((entry): boolean => _type.startsWith(entry));
```

So that we could config `DEBUG=true yarn test` to show debug logs, and `yarn test` by default does not show logs?

**Comment by jacogr** [comment]
In the above suggestion, the ability to "log all" gets lost. However is there is an option to check for wildcard (e.g. "*") and/or the indv. entries, it could work.
