### ISSUE TITLE
encode or decode string error

### ISSUE THREAD

**Issue by puti94** [polkadot-js/common#498]
When I use this library in react-native, stringToU8a or u8aToString function is use in TextDecoder or TextEncoder
```
let encoder;

function polyfilledEncode(value) {
  const u8a = new Uint8Array(value.length);

  for (let i = 0; i < value.length; i++) {
    u8a[i] = value.charCodeAt(i);
  }

  return u8a;
}

try {
  encoder = new TextEncoder();
} catch (error) {
  encoder = {
    encode: polyfilledEncode
  };
}
/**
 * @name stringToU8a
 * @summary Creates a Uint8Array object from a utf-8 string.
 * @description
 * String input values return the actual encoded `UInt8Array`. `null` or `undefined` values returns an empty encoded array.
 * @example
 * <BR>
 *
 * ```javascript
 * import { stringToU8a } from '@polkadot/util';
 *
 * stringToU8a('hello'); // [0x68, 0x65, 0x6c, 0x6c, 0x6f]
 * ```
 */


function stringToU8a(value) {
  if (!value) {
    return new Uint8Array([]);
  }

  return encoder.encode(value);
}
```

but when i use stringToU8a('测试')，It will produce incorrect results；
I'd like to have TextEncoder|TextDecoder support built in;
I found a library [fast-text-encoding](https://github.com/samthor/fast-text-encoding)

**Comment by jacogr** [comment]
I would suggest adding the correct polyfills to the RN application. The polyfills here will probably be completely removed as part of the 2.0 series. (There are way too many, and they are all for RN)

**Comment by puti94** [comment]
https://github.com/puti94/substrate-wallet/blob/master/nodeGlobalsShim.js
This is how I use it. I hope to add some notes on it
https://github.com/polkadot-js/ui/blob/master/packages/exampleReactNative/nodeGlobalsShim.js

**Comment by jacogr** [comment]
That seems 100% sane. If you feel like making a PR to the RN sample, it def. would be appreciated.

**Comment by puti94** [comment]
https://github.com/polkadot-js/ui/pull/260
I'd be happy to offer some help, but some checks were not successful.I'm not familiar with this

**Comment by jacogr** [comment]
Brilliant! Thank you. Those look like some transient errors.

Will close this one.
