### ISSUE TITLE
Support ECDSA(secp256k1) keypairs

### ISSUE THREAD

**Issue by akru** [polkadot-js/common#506]
**Motivation**

Currently Polkadot/Substrate [support](https://github.com/paritytech/substrate/blob/bc85d352681018e5b19369b758c013a52c5c3032/primitives/runtime/src/lib.rs#L166) three kinds of cryptographic primitives as `MultiSignature` data type:

* Ed25519
* Sr25519
* ECDSA

Unfortunately, polkadot-js support [first two](https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/types.ts) only. It's limiting using ECDSA keys for `subkey` CLI utility, which makes user experience pipeline a bit difficult.

**Proposal**

Introduce ECDSA keypair into polkadot-js crypto modules to support `secp256k1` crypto keys as same as Ed/Sr25519.

**Comment by jacogr** [comment]
Thanks for logging, it has been in the back on my mind, not sure why it was not logged. 

PRs are very welcome on this one, would love support, but it probably won’t happen soon.

**Comment by lovesh** [comment]
I would like to contribute this and submit over the next week. Anyone else already working on this?

**Comment by akru** [comment]
@lovesh I’m working on this issue as part of ECDSA integration grant.

**Comment by lovesh** [comment]
@akru Thanks for this.

**Comment by jacogr** [comment]
Closed in #589, released in 2.9.1
