### ISSUE TITLE
Keyring is not a constructor

### ISSUE THREAD

**Issue by gitcodeporter** [polkadot-js/common#540]
polkadot/keyring version is 2.4.1

const Keyring = require('@polkadot/keyring');
const phrase = mnemonicGenerate();
await cryptoWaitReady();
const keyring = new Keyring({ type: 'sr25519' });
const keyringPair = keyring.addFromMnemonic(phrase);

Error:
TypeError: Keyring is not a constructor

How to solve it?

**Comment by jacogr** [comment]
If you are using node, you need to import via

`const Keyring = require('@polkadot/keyring').default;`

There is an example here -

https://github.com/polkadot-js/common/blob/master/docs/examples/keyring/01_create_account/index.js

(For some reason the docs site is not up, so couldn't reference there)
