### ISSUE TITLE
Keyring address is different address then in Polkadot UI

### ISSUE THREAD

**Issue by faboweb** [polkadot-js/common#571]
When I am importing my seed into Polkadot UI I get an expected address. If I use `Keyring`, the `keyPair` object has an `address` property, that doesn't match the address in Polkadot UI. When I use the `keyPair` for signing, in the signed message the address actually is correct. Do I need to convert the `address` from the `keyPair` somehow?

**Comment by jacogr** [comment]
Pass the `ss58Format` with the correct chain value to the keyring constructor. When nothing is specified it always (as per convention) have to default to the Substrate generic default, which is 42.

**Comment by faboweb** [comment]
Ahhh! Ok nice to know. But why does the correct address show when signing a tx? And what is the Kusama prefix?

**Comment by jacogr** [comment]
the `ss58Format` is for human display and only for that. It does not affect the public keys at all. It doesn't matter what it is set at for signing to work.

**Comment by faboweb** [comment]
Why did you choose to go for such a prefix format that is not very visible over bech32 prefixes like in Cosmos?
