### ISSUE TITLE
Throw an error when the keypair is locked

### ISSUE THREAD

**Issue by h4x3rotab** [polkadot-js/common#576]
Currently the "locked" keypair has a secret key of zero:

https://github.com/polkadot-js/common/blob/697a452ba6be77b747dbf745bef790313ded8285/packages/keyring/src/pair/index.ts#L136-L138

`sign()` will return an invalid signature if a developer forgets to check `.isLocked` before signing:

https://github.com/polkadot-js/common/blob/697a452ba6be77b747dbf745bef790313ded8285/packages/keyring/src/pair/index.ts#L142-L143

 This is confusing to new developers. It's better to raise an error instead of returning a wrong signature here.

**Comment by jacogr** [comment]
PRs welcome if critical to your usecase, will probably take a while to get to.
