### ISSUE TITLE
Error: Expected hex value to convert

### ISSUE THREAD

**Issue by puffanddmx** [polkadot-js/common#704]
i got the below error if i run the below code.

 hexToU8a(json.encoded)) -> json.encoded is not the hex code as you see below. how to solve this ?
this is also defined in the link.

---------------------------------link---------------------------------------------
https://github.com/polkadot-js/apps/blob/fbacf652ecbbc6fd7cab5e2948877b9b33e2d514/packages/ui-keyring/src/account/restore.ts#L21

---------------code---------------------------------------------------
 var restoredPair = createPair(type1,
    { publicKey: keyringPairPubKey1},
    json.meta,
    hexToU8a(json.encoded));

  console.log(restoredPair);
  return
-----------------json---------------------------------------------
{
  address: '5G9tu22mpSLY14UZVP9sk4BZ2GSNbeFigGwubWuPPqkHLgLi',
  encoded: 'pSF+MAqzr0Mn/hR3CmOEoziwyAx7SuL8Nah9IDz/nVUAgAAAAQAAAAgAAAAr3TQuEHZFkLRzW7MLibcm3IwZ/DmxqdEzjKT8DUoZlrLxeoKFCVrFBasJHK0AIiWduF9t00AY48h0edRmARWKRNeUHfJD0jdBOhoMIXFCYh2i9lx+jGt4k4j/hw9QocG6by80w1MaPCyHt4g5u6dNi75h9D9LIQImilOX42vUbegifMB1vi6zVJAkXQww3CMt4ey4PO/M2DmnF4ee',
  encoding: {
    content: [ 'pkcs8', 'sr25519' ],
    type: [ 'scrypt', 'xsalsa20-poly1305' ],
    version: '3'
  },
  meta: { name: '', tags: '', whenCreated: 1602399794352 }
}

--------------------error----------------------------------------------
Error: Expected hex value to convert, found 'pSF+MAqzr0Mn/hR3CmOEoziwyAx7SuL8Nah9IDz/nVUAgAAAAQAAAAgAAAAr3TQuEHZFkLRzW7MLibcm3IwZ/DmxqdEzjKT8DUoZlrLxeoKFCVrFBasJHK0AIiWduF9t00AY48h0edRmARWKRNeUHfJD0jdBOhoMIXFCYh2i9lx+jGt4k4j/hw9QocG6by80w1MaPCyHt4g5u6dNi75h9D9LIQImilOX42vUbegifMB1vi6zVJAkXQww3CMt4ey4PO/M2DmnF4ee'
    at assert (/home/substrate_test_api/node_modules/@polkadot/util/assert.js:33:11)
    at hexToU8a (/home/substrate_test_api/node_modules/@polkadot/util/hex/toU8a.js:39:23)
    at main (/home/substrate_test_api/keygen.js:49:5)

**Comment by jacogr** [comment]
You are linking to an old commit on apps that does not support the new version 3 JSON structure. Look at master. As of keypair 3 it can be either hex or base64.

**Comment by puffanddmx** [comment]
Thanks
