### ISSUE TITLE
Odd issue when using serverless/lambda's with signatureVerify in util-crypto

### ISSUE THREAD

**Issue by FahdW** [polkadot-js/common#725]
During the first run of signatureVerify within a lambda function the function returns `{ crypto: 'none', isValid: false }` after the first run it will load `{ crypto: 'sr25519', isValid: true }` with no change to the request payload. Is there a scenario in which it will return none, and false during a verification even though the data is correct?

**Comment by jacogr** [comment]
Can you supply a snippet of the lambda in question, that will help in alignment.

**Comment by FahdW** [comment]
```
import { signatureVerify } from '@polkadot/util-crypto';
export default async function ({ utils, event, response, unprocessableRequest, notFound }) {
  let body;

  try {
    body = JSON.parse(event.body)
    if (!body.did || !body.signature || !body.userAddress) return unprocessableRequest();
  } catch {
    console.log(err);
    return unprocessableRequest();
  }
  const signature = signatureVerify(process.env.SIGNATURE_MESSAGE, body.signature, body.userAddress);
```
The snippet is pretty straight forward, but it is possible that a wasm is not initializing, the first run is always false, no crypto every subsequent one with at least the same data payload works fine. Just the first one is having an error.

**Comment by jacogr** [comment]
In that async, add a cryptoWait, https://polkadot.js.org/docs/util-crypto/FAQ#i-am-having-trouble-initializing-the-wasm-interface

**Comment by FahdW** [comment]
> In that async, add a cryptoWait, https://polkadot.js.org/docs/util-crypto/FAQ#i-am-having-trouble-initializing-the-wasm-interface before validating.

That was it, thanks!
