### ISSUE TITLE
Client-Side Emulation of Rust Blake2 256 Hashing

### ISSUE THREAD

**Issue by danforbes** [polkadot-js/common#787]
I am trying to calculate this hash with the Polkadot{JS} crypto utilities:
https://github.com/substrate-developer-hub/pallet-did/blob/8aae485ee74738b3f7611fa2c6af17cf7d23b4b6/src/lib.rs#L468

Here is my current attempt:
https://github.com/substrate-developer-hub/substrate-enterprise-sample/blob/6e47c313f048300b42c8aae6740e2284d603cab1/ui/src/components/OrganizationSelector.js#L35-L39

I am not able to successfully calculate the correct hash. Can you help me figure out what I'm doing wrong?

**Comment by jacogr** [comment]
None of this makes any sense - https://github.com/substrate-developer-hub/substrate-enterprise-sample/blob/6e47c313f048300b42c8aae6740e2284d603cab1/ui/src/components/OrganizationSelector.js#L36-L38

You are trying to manually do SCALE encoding here and getting it quite wrong.

```js
blake2AsHex(
  u8aConcat(
    // assuming addr is an ss58?
    decodeAddress(addr),
    // simple str -> u8a, no length-encoding, pure
    stringToU8a(name),
    // nonce as SCALE, LE
    nonce.toU8a() 
  )
)
```

**Comment by danforbes** [comment]
Current status: https://github.com/substrate-developer-hub/substrate-enterprise-sample/blob/2c01d67b03002cc94eb7cb9ed78ca8a1dc2b1da5/ui/src/components/OrganizationSelector.js#L36-L39

Still having problems. I'm also working with the authors of the DID pallet on this, @jacogr. cc: @gautamdhameja @jimmychu0807 @riusricardo @stiiifff

**Comment by jacogr** [comment]
This will certainly yield undefined decoding - 

`nonce.subn(1).toArray('le', 64)`

The second param here is bytes, not bits. You would remove a whole class of errors by using `bnToU8a(nonce.subn(1), { bitLength: 64 });`

**Comment by danforbes** [comment]
Thank you for your patience and suggestions, Jaco. I've updated the code but it's still not yielding the value I'm looking for:
https://github.com/substrate-developer-hub/substrate-enterprise-sample/blob/eee02c3e5601616a4850b4563776a9414ac78e2d/ui/src/components/OrganizationSelector.js#L36-L39

**Comment by jacogr** [comment]
Not sure about the `Org` param, thought I saw a `&[u8]`

However, it is passed from the caller are a `Vec<u8>`, so it needs to have length. In that case, it may actually it simpler -

```js
const hash  = registry.createType('(AccountId, Text, u64)', [addr, 'Org', nonce.subn(1)]).hash;
```

Not sure about that encoding, but just took a quick peek and not sure about the Vec -> u8 encoding.

**Comment by danforbes** [comment]
Yes! Thank you so much :tada:
