### ISSUE TITLE
how to generate polkadot address from an mnemonic phrase?

### ISSUE THREAD

**Issue by sollover** [polkadot-js/common#819]
hi,

I generated a mnemonic phrase with **@polkadot/util-crypto**. How can I generate public and private keys this phrase?

I tried this example:

`  const mnemonicAlice = mnemonicGenerate();

  console.log(`Generated mnemonic: ${mnemonicAlice}`);

  // Validate the mnemic string that was generated
  const isValidMnemonic = mnemonicValidate(mnemonicAlice);

  console.log(`isValidMnemonic: ${isValidMnemonic}`);

  // Create valid Substrate-compatible seed from mnemonic
  const seedAlice = mnemonicToMiniSecret(mnemonicAlice);

  // Generate new public/secret keypair for Alice from the supplied seed
  const { publicKey, secretKey } = naclKeypairFromSeed(seedAlice);

  console.log("pub key",publicKey)

  console.log("private key", secretKey)
` and than ı got the this result:

`Generated mnemonic: nuclear ankle type trigger craft snake clump scheme pact version develop hidden
isValidMnemonic: true
pub key Uint8Array(32) [
  145,  20, 192, 255, 192, 163, 174,  3,
   48, 201, 151,  25, 176, 247,  92, 11,
  244,  86, 248,  25, 225,  66, 188, 21,
  132, 112, 149,   7, 129,  48, 201, 69
]
private key Uint8Array(64) [
   48, 110, 152,  30,  69, 248,  36, 211,  91, 157, 182,
  190,  64, 111,  65,  66, 169, 130, 130,  52, 112, 205,
  188,  28, 136, 138, 178, 127, 236,  80,  29, 180, 145,
   20, 192, 255, 192, 163, 174,   3,  48, 201, 151,  25,
  176, 247,  92,  11, 244,  86, 248,  25, 225,  66, 188,
   21, 132, 112, 149,   7, 129,  48, 201,  69
]`

how can I convert this snippet to human readable :) ?

thank you

**Comment by jacogr** [comment]
`encodeAddress`(util-crypto)  to encode the publicKey to ss58.

**Comment by sollover** [comment]
> `encodeAddress`(util-crypto) to encode the publicKey to ss58.

thank you, I generate an address but this address an substrate address because it starts "5" how can I get an polkadot address (it will starts "1" ):

I added this code only:

  const  getAddress= ss58_encode(publicKey) 

The result: 5HeWArJWY7aUuoZqoTMCcaJuZow3JGQ3TffwQqa4bJn6LAxw

**Comment by jacogr** [comment]
```js
import { encodeAddress } from '@polkadot/util-crypto';

const PUBLIC = new Uint8Array([ 145, 20, 192, 255, 192, 163, 174, 3, 48, 201, 151, 25, 176, 247, 92, 11, 244, 86, 248, 25, 225, 66, 188, 21, 132, 112, 149, 7, 129, 48, 201, 69 ];)

// default prefix -> 5FLvxxfUzLCkVbFJqJQNuAXow1T987MtKfPvdafK4FG4Y2ft
console.log('Substrate', encodeAddress(PUBLIC)); 

// 0 is Polkadot => 14HE7HvYr7UDw8FpnwTP3KMxndSnpQv2QA8QnsefcLHaiQTD
console.log('Polkadot', encodeAddress(PUBLIC, 0));

// 2 is Kusama => FrYdH1MchDgFF4kc1DRo7tp5bjNvnB4n3Eg2EwGY3UZHGEq
console.log('Kusama', encodeAddress(PUBLIC, 2)); 
```

**Comment by jacogr** [comment]
Just a note - `mnemonicToSeed` is not Substrate compatible. Substrate uses `mnemonicToMiniSecret` (Hence the naming of `mnemonicToLegacySeed` in util-crypto, it is ETH/BTC-compatible, but non-Substrate standard)

**Comment by sollover** [comment]
thank you encode address works fine! 👍
