### ISSUE TITLE
Unable to generate keypair from random seed.

### ISSUE THREAD

**Issue by kingsley-einstein** [polkadot-js/common#827]
I  have tried to create a pair from URI using a random seed but I keep getting this error:

```sh
Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33
```

```ts
try {
   const keyring = new Keyring({ type: "sr25519", ss58Format });
   const miniSecret = randomAsHex(32);
   const pair = keyring.addFromUri(miniSecret, { name });
   return Promise.resolve({
    statusCode: 200,
    payload: {
     address: pair.address,
     privateKey: miniSecret
    }
   });
  } catch (error) {
   console.log(error);
   return Promise.reject(new Error(error.message));
  }
```

When I try to generate a mini secret from a randomly generated mnemonic, I get the error:

```sh
RuntimeError: unreachable
```

This is very similar to the example in the documentation: https://polkadot.js.org/docs/keyring/start/suri

**Comment by kingsley-einstein** [comment]
@gavofyork @AndreasGassmann

**Comment by jacogr** [comment]
Here is a working sample, from your code -

```js
import { Keyring } from '@polkadot/keyring';
import { cryptoWaitReady, randomAsHex } from '@polkadot/util-crypto';

async function main () {
  await cryptoWaitReady();

  const keyring = new Keyring({ type: 'sr25519', ss58Format: 2 });
  const seed = randomAsHex(32);
  const pair = keyring.addFromUri(miniSecret, { name: 'testing' });

  return {
    address: pair.address,
    seed: miniSecret
  };
}

main()
  .then((result) => {
    console.log(result);
    process.exit(0);
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

**Comment by kingsley-einstein** [comment]
> Here is a working sample, from your code as per [https://polkadot.js.org/docs/util-crypto/FAQ#i-am-having-trouble-initializing-the-](https://polkadot.js.org/docs/util-crypto/FAQ#i-am-having-trouble-initializing-the-wasm-interface)

Same problem

**Comment by jacogr** [comment]
Did you look at the linked repo - it is a runnable sample

**Comment by kingsley-einstein** [comment]
> Did you look at the linked repo - it is a runnable sample

Yes.

**Comment by jacogr** [comment]
Cloned, installed and ran it?

**Comment by kingsley-einstein** [comment]
> Cloned, installed and ran it?

not at all. I just did something similar. I'm using Typescript and it's the back-end for a multi-blockchain app. It was working before. It suddenly stopped working.

**Comment by kingsley-einstein** [comment]
> Cloned, installed and ran it?

I was initially using "mnemonicToMiniSecret" which was working but suddenly started throwing a Runtime error with the message "unreachable".

**Comment by jacogr** [comment]
Adjusting the above code in the same repo -

```js
import { Keyring } from '@polkadot/keyring';
import { u8aToHex } from '@polkadot/util';
import { cryptoWaitReady, randomAsHex, mnemonicGenerate, mnemonicToMiniSecret } from '@polkadot/util-crypto';

async function main () {
  await cryptoWaitReady();

  const keyring = new Keyring({ type: 'sr25519', ss58Format: 2 });

  console.log('      via seed', keyring.addFromUri(randomAsHex(32), { name: 'testing' }).address);
  console.log('  via mnemonic', keyring.addFromUri(mnemonicGenerate(), { name: 'testing' }).address);

  const miniSecret = u8aToHex(mnemonicToMiniSecret(mnemonicGenerate()));

  console.log('via minisecret', keyring.addFromUri(miniSecret, { name: 'testing' }).address);
}

main()
  .then((result) => {
    process.exit(0);
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```
  
Output -
  
```
        via seed ELw6v9JYz9nVUFJ92gHebPxzjDia2ueiF9MD8v5AZ3BiVaB
  via mnemonic FP1F463pA7JgC3nUaqUks8ukiRE9Kv2DpEK9uiMxqTBsf95
via minisecret H2Nijz3bYh9FAXi7TnqhBMrppBg2Mqko7gjk6GwwDJcFLpR
```

**Comment by jacogr** [comment]
So, it is a local environment issue on your side. I would suggest -

- check that your util/util-crypto/wasm is on the latest versions
- same with API
- ensure that there are not multiple of these installed

**Comment by kingsley-einstein** [comment]
> So, it is a local environment issue on your side. I would suggest -
> 
> * check that your util/util-crypto/wasm is on the latest versions
> * same with API
> * ensure that there are not multiple of these installed

I presume the latest @polkadot/util/util-crypto/wasm version is 5.2.3

**Comment by kingsley-einstein** [comment]
> So, it is a local environment issue on your side. I would suggest -
> 
> * check that your util/util-crypto/wasm is on the latest versions
> * same with API
> * ensure that there are not multiple of these installed

Still getting same issue

**Comment by kingsley-einstein** [comment]
@jacogr This is getting frustrating. It was initially working and now, it is suddenly giving problems.

**Comment by jacogr** [comment]
It is certainly environmental based on the setup when it "suddenly stops working". (Code-wise, it seems to align with the linked working sample).

"initially working" - "suddenly stopped" - what changes did you make to change the outcome?

**Comment by kingsley-einstein** [comment]
> It is certainly environmental based on the setup when it "suddenly stops working". (Code-wise, it seems to align with the linked working sample).
> 
> "initially working" - "suddenly stopped" - what changes did you make to change the outcome?

I made no change at all. Code has been the same since it was working. I was implementing a new coin when all of a sudden it stopped working.

**Comment by jacogr** [comment]
We've determined that the code you have is fine. Code doesn't "just break", so we know it is a change in environment caused by a change made. Do the following -

`cat yarn.lock| grep @polkadot/wasm-crypto` to ensure you don't have multiples. (`yarn dedupe` will adjust if there are)

**Comment by kingsley-einstein** [comment]
Thanks for your aid @jacogr . Issue has been resolved. It was the result of a conflicting library.
