### ISSUE TITLE
HD wallet from master publickey

### ISSUE THREAD

**Issue by shangpit** [polkadot-js/common#832]
- I Want to create a public key generation service from a master publickey like that
![extended-public-key](https://user-images.githubusercontent.com/49492179/104301189-ecb7f200-54f9-11eb-8586-db124f86e5eb.gif)
```
const publicKey: Uint8Array = Uint8Array.from([225, 95, 4, 13, 200, 121, 221, 237, 126, 160, 18, 77, 234, 92, 238, 25, 237, 169, 201, 10, 230, 101, 73, 153, 87, 71, 75, 45, 21, 248, 179, 82]);
const keyring: Keyring = new Keyring();
keyring.addFromAddress(publicKey);
const key = keyring.createFromUri(`//hex@gmail.com//aaa`)
const message = stringToU8a('this is our message');
const signature = key.sign(message);
```

I dont understand why can sign without a privatekey....
So that key-object here contains of private key???

**Comment by jacogr** [comment]
Yes, the pair object wraps the secret in a closure.

**Comment by shangpit** [comment]
How to separate them with Pokadot.js api @jacogr

**Comment by jacogr** [comment]
No, you cannot decode a private key from the publicKey. The `addFromAddress` is used in the cases where you want a list of contracts, e.g. in a keypair. You cannot sign with those at all.

The pairs does not expose the secret via any getters at all. It is inaccessible. If you want to derive a key from it, you can use the `.derive` function on the pair to create a new pair.

**Comment by shangpit** [comment]
i understand that pairs does not expose the secret via any getters. But to initialize a pair, we need a mnemonic <--- this is not secure. Imagine that in a cryptocurrency exchange project,  I just want to pass a master PUBLIC key and each user deposit wallet will derive from this PUBLIC key. And in another project i will store PRIVATE key to control balance and sign transaction. 

```project that initial from master public key```
![child-keys-advanced-public](https://user-images.githubusercontent.com/49492179/104396463-4b727f80-557d-11eb-891d-256646a9fddc.gif)

```project that hold private key to control balance```
![child-keys-advanced-private](https://user-images.githubusercontent.com/49492179/104396524-693fe480-557d-11eb-9854-41b0d41f1e46.gif)

**Comment by shangpit** [comment]
But the best thing about HD wallets is that you can generate new public keys ```without knowing the private keys for them```

**Comment by shangpit** [comment]
```js
import { sr25519DerivePublicSoft } from '@polkadot/wasm-crypto';

export function schnorrkelDerivePublic (publicKey: Uint8Array, chainCode: Uint8Array): Uint8Array {
  return sr25519DerivePublicSoft(publicKey, chainCode);
}

```
May be this is what i am finding

**Comment by jacogr** [comment]
You are speaking about soft-derivation - that is only available on sr25519. So providing `/a` (soft path) does the same derivation. But yes, it is not exposed as an option on addresses without doing is via the sr-specific function. (Pair derivation assumed full key derivation, even if just a soft path provided)
