### ISSUE TITLE
Export sr25519 vrf_{sign, verify} into util-crypto

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/common#840]
As per https://github.com/polkadot-js/wasm/pull/170

Prefer just using the extra version, if no extra bytes specified, pass as empty to the WASM layer.

It is very unlikely that this will end up in the keyring, although that may end up under a "{sign, verify}Deterministic" monicker with options for ed25519 and ecdsa as well.

(This won't be exposed on user-facing applications such as apps UI nor the extension, the signing interfaces there are specific and pin-point - this is only additional functionality on the builder-level)

**Comment by jacogr** [comment]
Once implemented, can look at removing the unused (non-extra) in the WASM layer.

**Comment by stiiifff** [comment]
> This won't be exposed on user-facing applications such as apps UI nor the extension, the signing interfaces there are specific and pin-point - this is only additional functionality on the builder-level

@jacogr Could we expose the vrfSign function in the injected Signer interface, and update the extension to support that use case ?

**Comment by jacogr** [comment]
The extension won't expose this. It is very specific use-only. The interface there needs to be kept as clean as possible so there is absolutely no confusion.

**Comment by stiiifff** [comment]
Fair enough, I understand.
Thinking out loud ... could it be exposed in separate interface that would only be injected if the user toggles an "experimental features" switch in the extension.

**Comment by jacogr** [comment]
No, the effort to do this is even worse and adding more code onto the pile. There is a single consistent signing interface that is exposed by the signer. Only this - https://github.com/polkadot-js/api/blob/master/packages/types/src/types/extrinsic.ts#L130-L145 (which is exactly what is needed to sign transactions and raw data for chain operations)

So I 100% understand the vrf capabilities for very specific use-cases -

1. Since the chain uses it, the JS side needs to have the capabilities to get to the same answer (be it in either a JS client or in any additional utility)

2. Some providers have been asking for it in the base to make their derivation compatible with what they have on other environments

Apart from those which both operate on a lower level, there is no real need to actually even have this on the keyring (which as I said, is actually super hacky with this added since there are 4 crypto types that now all need to conform to this sr25519-only interface in some way) and certainly not just "because it is there".
