### ISSUE TITLE
React-native: undefined is not a contructor - evaluation new UTE()

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/common#857]
I've got this type error when upgrading @polkadot/api of Parity Signer from 1.31.2 to 3.6.3 :see_no_evil:
The `textEncoder` from the stack brought me to common, and possibly `@polkadot/x-textencoder` but this UTE is nowhere to be found, so I might be wrong...

![image](https://user-images.githubusercontent.com/33178835/105643224-d8c3a700-5e8e-11eb-8da1-1331547228e3.png)

**Comment by jacogr** [comment]
UTE sounds familiar, but old. Not sure that is in the code anymore :(

**Comment by Tbaut** [comment]
I found it, in the util/polyfill. Let me find a link

**Comment by jacogr** [comment]
That was removed, I’m sure of it.

**Comment by Tbaut** [comment]
My @polkadot/util is indeed very old (everything's old anyway!), I wanted to go step by step, but it looks like I'll need to upgrade it all. <-- I tried this too, but everything broke too.

**Comment by Tbaut** [comment]
closing, it's def not actual any more :)
