### ISSUE TITLE
Add eth addresses to test dev addresses

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/common#899]
We want to add eth addresses when running a dev node (and prefund them in our genesis)
If I understand what you said here https://github.com/polkadot-js/apps/issues/4467#issuecomment-768233896 we can do that as long as we provide the secret key and the public key so that it can be created (and not derived) by createPair.
In fact, it looks like Gerald has already been added to the dev keyring for ethereum (as I have tested).
Can we add others addresses that would be considered canonic dev addresses for eth henceforth?

**Comment by jacogr** [comment]
Does Gerald actually show up on the apps UI?

**Comment by joelamouche** [comment]
We are flexible on what the standard should be.
We could go for "bottom drive obey lake curtain smoke basket hold race lonely fit walk" if that's what's standard.

<img width="1022" alt="Screenshot 2021-02-26 at 11 36 03" src="https://user-images.githubusercontent.com/16758383/109309895-29d70a00-7844-11eb-9627-0df9105eac5b.png">

**Comment by jacogr** [comment]
If we stick to that, quite happy to adjust with whatever paths makes sense.

**Comment by joelamouche** [comment]
>Does Gerald actually show up on the apps UI?

Not sure if it was saved or it showed up. What would prevent it from displaying? Is there a filter on pair type?

**Comment by jacogr** [comment]
As far as I know, it just uses the defaults, doesn't try to pass through a type. So there may be some mangling required. Let's put it this way, if Alice/Bon/Charlie/... showed up, it is probably incorrect since your logic excluded those.

**Comment by joelamouche** [comment]
I'm sorry I don't quite understand. Do you mind pointing to me where the dev pairs are declared and where they are loaded please?

**Comment by jacogr** [comment]
Here - https://github.com/polkadot-js/common/blob/master/packages/keyring/src/testing.ts

The reason why the public/secret is already derived here (shown as hex, not suri) and not derived via mnemonic is that the mnemonic -> seed takes quite a while, i.e. it would have a delay of 1-2s on the UI layer as opposed to the approach here.

**Comment by joelamouche** [comment]
Thanks. Where in the UI can I see this function being called. It's quite hard to understand without having access to ui-keyring's loadAll(). It doesn't seem to call createTestPairs in the compiled js version.
I need to verify that it's passing on the type

**Comment by jacogr** [comment]
https://github.com/polkadot-js/ui/blob/master/packages/ui-keyring/src/Base.ts#L105-L121

**Comment by joelamouche** [comment]
Thanks!

![Screenshot 2021-03-02 at 11 07 47](https://user-images.githubusercontent.com/16758383/109632677-99e8d700-7b47-11eb-968e-a59a49416ab7.png)
Looks like dev addresses work after all...
I just needed to remove the isEthereum check on dev

**Comment by joelamouche** [comment]
https://github.com/polkadot-js/apps/pull/4763
