### ISSUE TITLE
create a valid wallet for polkadot network

### ISSUE THREAD

**Issue by samanyousefi** [polkadot-js/common#907]
how i can create a valid public-private key to using in the Polkadot network.

**Comment by samanyousefi** [comment]
i used that like sample code but the result is not a valid address

description about dot coin valid structure 
https://wiki.polkadot.network/docs/en/learn-accounts


**sample code:**

**// modules**

          const {
                    mnemonicGenerate,
                    mnemonicToMiniSecret,
                    mnemonicValidate,
                    naclKeypairFromSeed,
                    naclKeypairFromRandom
                } = require('@polkadot/util-crypto');


**// Codes**

            // Create mnemonic string for Alice using BIP39
            const mnemonicAlice = mnemonicGenerate();

            console.log(`Generated mnemonic: ${mnemonicAlice}`);

            // Validate the mnemic string that was generated
            const isValidMnemonic = mnemonicValidate(mnemonicAlice);

            console.log(`isValidMnemonic: ${isValidMnemonic}`);

            // Create valid Substrate-compatible seed from mnemonic
            const seedAlice = mnemonicToMiniSecret(mnemonicAlice);

            // Generate new public/secret keypair for Alice from the supplied seed
            // const { publicKey, secretKey } = naclKeypairFromSeed(seedAlice);
            const { publicKey, secretKey } = naclKeypairFromRandom();

            console.log(publicKey, secretKey)
            console.log(Buffer.from(publicKey).toString('hex'))
            console.log(Buffer.from(secretKey).toString('hex'))

            }



**Result:**


**// Public Key**
Uint8Array(32) [
  153, 130, 213, 236, 106, 230,  48,  97,
   14, 214, 110, 131, 142,  80, 183, 130,
   37, 174,  64,  26, 166, 130,  35, 251,
   78,  60, 119,  73,  33, 216, 205, 203
] 

**// Secret Key**
Uint8Array(64) [
  133, 224,  82, 216,  52,  55, 143, 131, 154,  87, 207,
   36,  47, 236, 139, 165, 124,  44, 131,  34, 238, 239,
  111, 226, 232,  22,  55, 122,  13, 179,   0, 189, 153,
  130, 213, 236, 106, 230,  48,  97,  14, 214, 110, 131,
  142,  80, 183, 130,  37, 174,  64,  26, 166, 130,  35,
  251,  78,  60, 119,  73,  33, 216, 205, 203
]

**// Public Key**
9982d5ec6ae630610ed66e838e50b78225ae401aa68223fb4e3c774921d8cdcb

**// Secret Key**
85e052d834378f839a57cf242fec8ba57c2c8322eeef6fe2e816377a0db300bd9982d5ec6ae630610ed66e838e50b78225ae401aa68223fb4e3c774921d8cdcb

**Comment by jacogr** [comment]
What is not a valid address? This creates valid addresses as per specification - and all test-cases align with Subkey. Additionally is is used by all the JS wallets in the ecosystem.

What are you expecting that you don't see?

**Comment by samanyousefi** [comment]
the public key is not a valid address for Polkadot, a valid public key must start with 1 character and also must be valid on the website:  [polkascan.io](https://polkascan.io/polkadot) I just want a code or solution for creating the polka dot wallet.

**Comment by jacogr** [comment]
No. What you are viewing on Polkadsan is the publicKey encoded with ss58 as an address. Publick key bytes themselves do not start with a 1.

So, as suggested - `encodeAddress(publicKey, 0)` (the 0 is the Polkadot ss58 prefix, 2 for Kusama, etc.)

**Comment by samanyousefi** [comment]
thank you @jacogr, i used this document examples codes, and that  returned for me some addresses:

**Polkadot 1NthTCKurNHLW52mMa6iA8Gz7UFYW5UnM3yTSpVdGu4Th7h**
Substrate generic 5CSbZ7wG456oty4WoiX6a1J88VUbrCXLhrKVJ9q95BsYH4TZ
Kusama CxDDSH8gS7jecsxaRL9Txf8H5kqesLXAEAEgp76Yz632J9M

my target publicKey is Polkadot, but Polkscan result is: 
"No results found for 1NthTCKurNHLW52mMa6iA8Gz7UFYW5UnM3yTSpVdGu4Th7h"

you can see that message in this URL:
https://polkascan.io/polkadot/analytics/search/1NthTCKurNHLW52mMa6iA8Gz7UFYW5UnM3yTSpVdGu4Th7h

and my other question is how I can get the private key of that created publicKey i above.

**Comment by jacogr** [comment]
Polkascan will only show addresses that have received funds - before that and without an existential deposit, they do not appear in the chain state. (Same as Subscan). So it is 100% correct that they cannot find the address, since it has not have funds.

The private key is not derivable from the publicKey - that would mean that anybody with an address has access to the funds. They are a pair. The keyring doesn't even expose the `secretKey` in any getters. In your example above, you create a public/private pair.

**Comment by samanyousefi** [comment]
so i cant create a wallet for polka dot with this package?

**Comment by jacogr** [comment]
This is how an account shows up on an explorer -

- a user creates a public/private key combination
- from the public key an human-readable ss58 is created
- funds (> existential deposit) are send to that address from another address
- once it is in the chain state (> existential), the explorers show it

Accounts are only reflected in the chain state when it has an existential value.

**Comment by samanyousefi** [comment]
thank you, i get it but please tell me after i run the following code and i get the public key how i can send money, i don't have a private key.




// known mnemonic, well, now it is - doesn't use it for funds
const MNEMONIC = 'sample split bamboo west visual approve brain fox arch impact relief smile';

// type: ed25519, ssFormat: 42 (all defaults)
const keyring = new Keyring();
const pair = keyring.createFromUri(MNEMONIC);

// use the default as setup on init
// 5CSbZ7wG456oty4WoiX6a1J88VUbrCXLhrKVJ9q95BsYH4TZ
console.log('Substrate generic', pair.address);

// adjust the default ss58Format for Kusama
// CxDDSH8gS7jecsxaRL9Txf8H5kqesLXAEAEgp76Yz632J9M
keyring.setSS58Format(2);
console.log('Kusama', pair.address);

// adjust the default ss58Format for Polkadot
// 1NthTCKurNHLW52mMa6iA8Gz7UFYW5UnM3yTSpVdGu4Th7h
keyring.setSS58Format(0);
console.log('Polkadot', pair.address);

**Comment by samanyousefi** [comment]
in the following code, i have an address and also a private key (secret) but the secret key is an array, how i can encode that like publicKey with an encoded address method.  


      const {
            mnemonicGenerate,
            mnemonicToMiniSecret,
            mnemonicValidate,
            naclKeypairFromSeed,
            naclKeypairFromRandom,encodeAddress
        } = require('@polkadot/util-crypto');

        const {
            Keyring
        } = require('@polkadot/keyring');

            // Create mnemonic string for Alice using BIP39
            const mnemonicAlice = mnemonicGenerate();

            // Validate the mnemic string that was generated
            const isValidMnemonic = mnemonicValidate(mnemonicAlice);

            // Create valid Substrate-compatible seed from mnemonic
            const seedAlice = mnemonicToMiniSecret(mnemonicAlice);

            const { publicKey, secretKey } = naclKeypairFromRandom();

            console.log(encodeAddress(publicKey, 0),'public')
            console.log(secretKey,'secret')


 following code result :

**public key**: 14cPULDYejY4nwi5AiRDTzPHxhiDMqwja1w2rQrxkjTLeivT 

**private key**: Uint8Array(64) [
   32, 189,  11, 140,  32, 149, 221,  96, 231,  77, 255,
   79, 164, 125, 134, 200, 229, 172, 188, 192,  32,  91,
   50,  50, 228,  55,  76,  93, 224, 247,  78, 174, 159,
  177, 239,  53, 183, 206, 223,  74,  47,  15, 101, 254,
  124,  70, 101, 112,  67, 123, 188,  51, 142,  23, 174,
  135, 183, 159, 148, 177, 161,  19, 200, 249
]

**Comment by jacogr** [comment]
The private key doesn't get encoded as an address. The public key does.

The keyring doesn't need to expose the private key since it allows you to perform signing operations with the pair - signing is the only area where a private key is needed.

**Comment by samanyousefi** [comment]
how can I store this private key in the database?

**Comment by jacogr** [comment]
If you wish to store it directly - not using the keyring exports (i.e. the toJSON), your approach above of creating it directly via the lower-level libraries is best.
