### ISSUE TITLE
Public key / Private key encryption using polkadot lib?

### ISSUE THREAD

**Issue by SachinSWN** [polkadot-js/common#929]
I'm building a substrate blockchain backed by polkadot js. While working on a task I have a requirement of public/private key encryption and decryption. for ex: Bob wants to send Alice an encrypted email. To do this, Bob takes Alice's public key and encrypts his message to her. Then, when Alice receives the message, she takes the private key that is known only to her in order to decrypt the message from Bob. Does anyone know how this is done through Polkadot js library? Help will be appreciated!

**Comment by jacogr** [comment]
For ed25519 pairs there is a encrypt/decrypt pairing -

- https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/nacl/encrypt.ts
- https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/nacl/decrypt.ts

It is not available for sr25519 (see https://github.com/polkadot-js/common/issues/633), nor ecdsa

**Comment by SachinSWN** [comment]
Thank You..it was really helpful!

**Comment by SachinSWN** [comment]
without NaclBoxKeyPair, can we encrypt/decrypt message using the normal public key and private key pair which a nemonic already have ?

**Comment by jacogr** [comment]
No, there is no sr25519 exposed interfaces, see https://github.com/polkadot-js/common/issues/633
