### ISSUE TITLE
Address to EVM and vice versa not consistent

### ISSUE THREAD

**Issue by ayusht11** [polkadot-js/common#931]
My understanding is we should be able to convert a substrate compatible address to Ethereum EVM compatible address and vice versa. 

Replication code:

```js
const { addressToEvm, evmToAddress } = require("@polkadot/util-crypto");
const { u8aToHex } = require("@polkadot/util");

// Test is based on this Spec: https://github.com/polkadot-js/common/blob/v6.0.5/packages/util-crypto/src/address/evmToAddress.spec.ts
let u8a = addressToEvm("5FrLxJsyJ5x9n2rmxFwosFraxFCKcXZDngRLNectCn64UjtZ", false);
let result = u8aToHex(u8a);
console.log(result);
console.log(result == "0xd43593c715fdd31c61141abd04a99fd6822c8558"); 

result = evmToAddress(result, 42, 'keccak');
console.log(result);
console.log(result === "5FrLxJsyJ5x9n2rmxFwosFraxFCKcXZDngRLNectCn64UjtZ");
result = evmToAddress(u8a, 42, 'keccak');
console.log(result);
console.log(result === "5FrLxJsyJ5x9n2rmxFwosFraxFCKcXZDngRLNectCn64UjtZ");
```

output:

```sh
0xa7839fbfca6da129ff9e2ff521115b7eb4213b21
false
5E5YNid584q9DcXyTVBbAZdxC88RcT6FcM1RZEqwBFTo3i7z
false
5E5YNid584q9DcXyTVBbAZdxC88RcT6FcM1RZEqwBFTo3i7z
false
```

All the results return false. I have also tried with `blake2` and it is still incorrect:

```js
const { addressToEvm, evmToAddress } = require("@polkadot/util-crypto");
const { u8aToHex } = require("@polkadot/util");

// Test is based on this Spec: https://github.com/polkadot-js/common/blob/v6.0.5/packages/util-crypto/src/address/evmToAddress.spec.ts
let u8a = addressToEvm("5FrLxJsyJ5x9n2rmxFwosFraxFCKcXZDngRLNectCn64UjtZ", false);
let result = u8aToHex(u8a);
console.log(result);
console.log(result == "0xd43593c715fdd31c61141abd04a99fd6822c8558"); 

result = evmToAddress(result, 42, 'blake2');
console.log(result);
console.log(result === "5FrLxJsyJ5x9n2rmxFwosFraxFCKcXZDngRLNectCn64UjtZ");
result = evmToAddress(u8a, 42, 'blake2');
console.log(result);
console.log(result === "5FrLxJsyJ5x9n2rmxFwosFraxFCKcXZDngRLNectCn64UjtZ");
```

output:

```sh
0xa7839fbfca6da129ff9e2ff521115b7eb4213b21
false
5CgqcL5JQyjsHdMYFDEdE8zBgVeChs7qkAUaNEawKcsR42qi
false
5CgqcL5JQyjsHdMYFDEdE8zBgVeChs7qkAUaNEawKcsR42qi
false
```

Please let me know if I am missing something.

**Comment by jacogr** [comment]
Not an expert on this, since it was contributed and have not used it myself. However - when going from evm to address, there is a secp256k1 hash - that creates a one-way direction.

In this case I believe the correct answer would be to compare what the code does here to what it does on the Rust evm pallet side. 

https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/address/evmToAddress.ts
https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/address/addressToEvm.ts

**Comment by ayusht11** [comment]
Hi, @jacogr thanks for responding quickly, can you point me to the pallet code?

Also, in case the code is not intended to be bi-directional, it would be a good idea to update the comments describing the util as well as function names.

**Comment by jacogr** [comment]
No idea, I believe it is in the frontier repo - https://github.com/paritytech/frontier/tree/master/frame/evm

But will take quite some time for me to find it in there, not really familiar with the evm stuff at all. But, yes, needs to be compared to see what it does in there. (I guess I would start searching for the `evm:` string - since that seems to be used at least for the hashing and then untangle from there to see if the JS side aligns or not...)

**Comment by ayusht11** [comment]
This file in the Frontier repo has a different way of calculating EVM addresses:

https://github.com/paritytech/frontier/blob/cc1040c13f7e78aef94b8a5c4fcf0d1b05db0cd5/template/examples/contract-erc20/create-erc20.ts#L58

```js
const {  decodeAddress, encodeAddress, blake2AsHex, addressToEvm, evmToAddress } = require("@polkadot/util-crypto");


const aliceEvmAccount = `0x${blake2AsHex(decodeAddress("5FrLxJsyJ5x9n2rmxFwosFraxFCKcXZDngRLNectCn64UjtZ"), 256).substring(26)}`;
console.log(aliceEvmAccount);
console.log(aliceEvmAccount == "0xd43593c715fdd31c61141abd04a99fd6822c8558"); 
```
output:

```bash
0x39d3812be6d01bc80077ebe92e2e25749ab1d814
false
```
But it still does not match the desired output and is also different from the values returned above.

**Comment by thanhtung6824** [comment]
Same issue. I ask in the Substrate technical group but no response. 
I believe the evmToAddress is correct because when converting evmToAddress and transfer token to the converted address, the balance increase. So I think the problem is addressToEvm function @jacogr

**Comment by jacogr** [comment]
If there is a bug, as always, PRs welcome if this is urgent to anybody. 

It will be still quite a bit of time before I'm able to circle back to this or even have a look. (Not actually familiar with this at all, never used the pallet, this was all contributed so will be a first foray looking at what frontier actually does)

**Comment by thanhtung6824** [comment]
No, I think it's not a bug, as you said because it's one-way so cannot be reversed.

I guess the only way to archive that is custom impl the trait AddressMapping<A> in frontier repo, define your own format for address translation and make it can be reversed back
