### ISSUE TITLE
How much overhead does encodeAddress method have?

### ISSUE THREAD

**Issue by Lebed-kun** [polkadot-js/common#950]
Firstly, I checked every address from some list applying function that utilizes "encodeAddress" from "@polkadot/util-crypto" in my api. Then I removed this function from checking address and my api works more times faster. So do you have any benchmarks on polkadot-js utils methods?

**Comment by jacogr** [comment]
Quite a bit - https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/address/encode.ts

1. It does decoding first (for re-encoding)
2. It does a large number of sanity checks

There are no benchmarks available. PRs for optimizations are always welcome, but the focus has always been on correctness vs speed, so benchmarking has never been done.

**Comment by jacogr** [comment]
PS: For checking, the latest utils do have validity checks, which _may_ be faster, however it still untilizes a decoding method
