### ISSUE TITLE
"Invalid injected scrypt params found" while trying to load JSON file - WESTEND

### ISSUE THREAD

**Issue by emenni** [polkadot-js/common#973]
[5FYNFATD.json.zip](https://github.com/polkadot-js/apps/files/6438610/5FYNFATD.json.zip)
Hello, 

 I created an account not in polkadot-js.org but wish to have it there. Is that  supposed to work ?  Error was on westend. Password is "mypassword".

**Comment by emenni** [comment]
I forgot to mention that due to testing while importing, I have manually included   

"type": [
      "scrypt",
      "xsalsa20-poly1305"
    ],

From the code bellow, I get this:


    // Convert the account data to JSON and format it for readability   
    const accountData = JSON.stringify(keyring.toJson(newAccount.address));
{
    "encoded": "MFMCAQEwBQYDK2VwBCIEIGjecdG5m/9WBv5wYnz3KplmQGJQ0f+oipIDQXkc5LZH9wyzQjw1/uJIn9TBOfVdUxUI4qQRzBO2QQmDMtfQKsWhIwMhAFaQsiDBPLuyZoBhCy50+RtduQ9vQNxPlOqS2VxPiGgP",
    "encoding": {
        "content": [
            "pkcs8",
            "sr25519"
        ],
        "type": [
            "none"
        ],
        "version": "3"
    },
    "address": "5E2CxZvZhrttYgbUiyMxZLAcBrN6ewTKEGb8XFzRu9zNQUUs",
    "meta": {
        "name": "new keypair"
    }
}

**Comment by jacogr** [comment]
Ahhh... ok. So... the "none" means it is not encoded. First run `pair.encodePkcs8("mypassword")` on the pair, then `toJSon` it. The `///<password>` is for the derivation, the `<password>` in encode is to encrypt it.

**Comment by emenni** [comment]
my bad, sorry. 

I'm a bit lost here.... 

 I tried the code below, but got the same error: 

const accountData = JSON.stringify(keyring.toJson(newAccount.address,keyring.pairs[0].encodePkcs8("mypass")), null, 2);

**Comment by jacogr** [comment]
It is 2 steps -

- encode the pair first 
- output the JSON secondly
