### ISSUE TITLE
`signatureVerify` fails silently for sr25519 if the WASM interface is not initialized

### ISSUE THREAD

**Issue by lsaether** [polkadot-js/common#980]
If the WASM interface is not initialized then `signatureVerify` fails silently, causing confusion on why a valid signature would fail the check. Example:

```js
const res = UtilCrypto.signatureVerify(msg, signature, pubkey);
console.log(res);
/**
{
  crypto: 'none',
  isValid: false,
  publicKey: Uint8Array(32) [
    186,  68, 238,  70,  31, 165,  51, 163,
    247, 188, 152, 130, 166, 112, 208,  98,
    129,  10, 234,  61,  34,  82, 120, 204,
    242, 129,  78, 138,  70, 205, 255,  64
  ]
}
*/
```

Allowing the WASM interface to initialize solves the problem:

```js
await new Promise(res => setTimeout(() => res(true), 1000));
const res = UtilCrypto.signatureVerify(msg, signature, pubkey);
console.log(res);
/**
{
  crypto: 'sr25519',
  isValid: true,
  publicKey: Uint8Array(32) [
    186,  68, 238,  70,  31, 165,  51, 163,
    247, 188, 152, 130, 166, 112, 208,  98,
    129,  10, 234,  61,  34,  82, 120, 204,
    242, 129,  78, 138,  70, 205, 255,  64
  ]
}
*/
```

`signatureVerify` should bubble up the WASM not initialized error instead of failing silently.

**Comment by jacogr** [comment]
This is a wontfix. The issue is that the sr verify throws itself. Not going down the route of matching error strings, and not detecting for WASM where the signature can be anything, including WASM-not-needed. My suggestion is to always init wasm if you use anything from util-crypto - not only does it speed things up,

**Comment by lsaether** [comment]
Fair enough, although it would be nice to at least have this documented as it's not immediately clear why the signature verification does not work until you try it with sr verify itself (that's what I did).

**Comment by jacogr** [comment]
PRs welcome to the docs repo, always really appreciate footguns.
